use std::cell::RefCell;
use kyc_core::ast::*;
use crate::mir::*;

thread_local! {
    static TYPE_ALIAS_CACHE: RefCell<std::collections::HashMap<String, AstType>> = RefCell::new(std::collections::HashMap::new());
}

pub mod ctx;
pub use self::ctx::*;
pub mod types;
pub use self::types::*;
pub mod helpers;
pub use self::helpers::*;
pub mod stmt;
pub mod expr;
pub mod function;

/// Lower a type-checked KL program to MIR.
pub struct Lowerer {
    fn_returns: RefCell<std::collections::HashMap<String, MirType>>,
    /// Maps async function name → declared return type (before replacing with i64)
    async_fn_returns: RefCell<std::collections::HashMap<String, MirType>>,
    struct_defs: RefCell<std::collections::HashMap<String, Vec<(String, MirType)>>>,
    class_constructor_map: RefCell<std::collections::HashMap<String, String>>,
    const_values: RefCell<std::collections::HashMap<String, Expr>>,
    /// Method dispatch table: class_name -> (method_name -> mangled_function_name).
    /// Built during lower_program by scanning ClassMember::Method entries.
    /// Used to lower `obj.method(args)` into `Call ClassName::method(obj, args...)`.
    method_table: RefCell<std::collections::HashMap<String, std::collections::HashMap<String, String>>>,
    /// Static method mangled names (no `this` param).
    static_methods: RefCell<std::collections::HashSet<String>>,
    /// Maps each class to its optional parent class name, used to walk the
    /// inheritance chain when resolving method calls (polymorphism/override).
    class_parent_map: RefCell<std::collections::HashMap<String, Option<String>>>,
    /// Enum variant index map: enum_name -> (variant_name -> index)
    enum_variants: RefCell<std::collections::HashMap<String, std::collections::HashMap<String, usize>>>,
    /// Counter for generating unique closure function names.
    closure_counter: RefCell<usize>,
    /// Closure functions generated during lowering.
    closure_functions: RefCell<Vec<MirFunction>>,
    /// Counter for generating unique async wrapper function names.
    async_counter: RefCell<usize>,
    /// Async wrapper functions generated during lowering.
    async_functions: RefCell<Vec<MirFunction>>,
    /// Generic struct templates (structs with type_params).
    generic_struct_templates: RefCell<std::collections::HashMap<String, StructDecl>>,
    /// Generic function templates (functions with type_params).
    generic_function_templates: RefCell<std::collections::HashMap<String, FunctionDecl>>,
    /// Generic class methods keyed by class name, for monomorphization during struct literal lowering.
    generic_class_methods: RefCell<std::collections::HashMap<String, Vec<FunctionDecl>>>,
    /// All function declarations (for default-value resolution at call sites).
    function_decls: RefCell<std::collections::HashMap<String, FunctionDecl>>,
    /// Specialized MIR functions generated by monomorphization.
    specialized_mir_functions: RefCell<Vec<MirFunction>>,
    /// Field defaults: class_name → (field_name → default_expr)
    field_defaults: RefCell<std::collections::HashMap<String, std::collections::HashMap<String, Expr>>>,
}

impl Lowerer {
    pub fn new() -> Self {
        Self {
            fn_returns: RefCell::new(std::collections::HashMap::new()),
            async_fn_returns: RefCell::new(std::collections::HashMap::new()),
            struct_defs: RefCell::new(std::collections::HashMap::new()),
            class_constructor_map: RefCell::new(std::collections::HashMap::new()),
            const_values: RefCell::new(std::collections::HashMap::new()),
            method_table: RefCell::new(std::collections::HashMap::new()),
            static_methods: RefCell::new(std::collections::HashSet::new()),
            class_parent_map: RefCell::new(std::collections::HashMap::new()),
            enum_variants: RefCell::new(std::collections::HashMap::new()),
            closure_counter: RefCell::new(0),
            closure_functions: RefCell::new(Vec::new()),
            async_counter: RefCell::new(0),
            async_functions: RefCell::new(Vec::new()),
            generic_struct_templates: RefCell::new(std::collections::HashMap::new()),
            generic_function_templates: RefCell::new(std::collections::HashMap::new()),
            generic_class_methods: RefCell::new(std::collections::HashMap::new()),
            function_decls: RefCell::new(std::collections::HashMap::new()),
            specialized_mir_functions: RefCell::new(Vec::new()),
            field_defaults: RefCell::new(std::collections::HashMap::new()),
        }
    }
    /// Lower a program to a MirModule.
    pub fn lower_program(&self, program: &Program) -> MirModule {
        // Pre-scan type alias definitions — must happen before function pre-scans
        // so that ast_type_to_mir can resolve alias names during fn_returns population.
        TYPE_ALIAS_CACHE.with(|cache| {
            let mut aliases = cache.borrow_mut();
            aliases.clear();
            for decl in &program.declarations {
                if let Decl::TypeAlias(t) = decl {
                    aliases.insert(t.name.clone(), t.type_.clone());
                }
            }
        });

        // Pre-scan struct declarations to build struct definition map
        // Two-pass: first register all struct/class names, then resolve field types
        // with the complete map so nested struct references work.
        // Generic structs (those with type_params) are stored as templates for later
        // monomorphization and skipped from normal struct_defs registration.
        {
            let mut struct_defs = self.struct_defs.borrow_mut();
            let mut generic_templates = self.generic_struct_templates.borrow_mut();
            struct_defs.clear();
            generic_templates.clear();
            // Pass 1: insert all names with empty field lists
            for decl in &program.declarations {
                if let Decl::Struct(s) = decl {
                    if !s.type_params.is_empty() {
                        generic_templates.insert(s.name.clone(), s.clone());
                    } else {
                        struct_defs.insert(s.name.clone(), vec![]);
                    }
                }
                if let Decl::Class(c) = decl {
                    if !c.type_params.is_empty() {
                        // Generic class — store as struct template
                        generic_templates.insert(c.name.clone(), StructDecl {
                            name: c.name.clone(),
                            type_params: c.type_params.clone(),
                            fields: c.members.iter().filter_map(|m| {
                                if let ClassMember::Field(f) = m { Some(f.clone()) } else { None }
                            }).collect(),
                            span: c.span.clone(),
                        });
                    } else {
                        struct_defs.insert(c.name.clone(), vec![]);
                    }
                }
                if let Decl::Enum(e) = decl {
                    struct_defs.insert(e.name.clone(), vec![]);
                }
            }
            // Pass 2: resolve field types with full struct_defs map
            for decl in &program.declarations {
                if let Decl::Struct(s) = decl {
                    if !s.type_params.is_empty() {
                        continue; // Generic struct — skip, monomorphized on use
                    }
                    let fields: Vec<(String, MirType)> = s.fields.iter()
                        .map(|f| (f.name.clone(), ast_type_to_mir(&f.type_, Some(&struct_defs))))
                        .collect();
                    struct_defs.insert(s.name.clone(), fields);
                }
                if let Decl::Class(c) = decl {
                    if !c.type_params.is_empty() {
                        continue; // Generic class — monomorphized on use
                    }
                    let fields = Self::collect_class_fields(c, &program, &struct_defs);
                    struct_defs.insert(c.name.clone(), fields);
                }
                if let Decl::Enum(e) = decl {
                    // Enums are represented as tagged unions: { disc: I32, payload: I64 }
                    let fields = vec![
                        ("disc".to_string(), MirType::I32),
                        ("payload".to_string(), MirType::I64),
                    ];
                    struct_defs.insert(e.name.clone(), fields);
                }
            }
            // Register tuple return types in struct_defs
            for decl in &program.declarations {
                if let Decl::Function(f) = decl {
                    if let Some(ref rt) = f.return_type {
                        if let AstType::Generic { name, args, .. } = rt {
                            if name == "tuple" {
                                let field_types: Vec<(String, MirType)> = args.iter().enumerate()
                                    .map(|(i, el)| (format!("_{}", i), ast_type_to_mir(el, Some(&struct_defs))))
                                    .collect();
                                let type_suffix: String = args.iter()
                                    .map(|a| match a {
                                        AstType::Primitive { name, .. } => name.clone(),
                                        _ => "x".to_string(),
                                    })
                                    .collect();
                                let struct_name = format!("_tuple_{}_{}", field_types.len(), type_suffix);
                                struct_defs.entry(struct_name)
                                    .or_insert_with(|| field_types);
                            }
                        }
                    }
                }
            }
            // Register built-in TypeInfo struct for type introspection
            struct_defs.entry("TypeInfo".to_string()).or_insert_with(|| vec![
                ("name".to_string(), MirType::Str),
                ("kind".to_string(), MirType::Str),
                ("size".to_string(), MirType::I32),
            ]);
        }

        // Populate field defaults for classes
        {
            let mut fds = self.field_defaults.borrow_mut();
            fds.clear();
            for decl in &program.declarations {
                if let Decl::Class(c) = decl {
                    if !c.type_params.is_empty() { continue; }
                    let mut defaults = std::collections::HashMap::new();
                    for member in &c.members {
                        if let ClassMember::Field(f) = member {
                            if let Some(ref default_expr) = f.default {
                                defaults.insert(f.name.clone(), (**default_expr).clone());
                            }
                        }
                    }
                    fds.insert(c.name.clone(), defaults);
                }
            }
        }

        // Pre-scan module-level constants and immutable variables
        {
            let mut cv = self.const_values.borrow_mut();
            cv.clear();
            for decl in &program.declarations {
                match decl {
                    Decl::Constant(c) => {
                        cv.insert(c.name.clone(), *c.value.clone());
                    }
                    Decl::Variable(v) => {
                        // Immutable module-level variables are inlined like
                        // constants — their value never changes at runtime
                        if !v.is_mutable {
                            cv.insert(v.name.clone(), *v.value.clone());
                        }
                    }
                    _ => {}
                }
            }
        }

        // Pre-scan enum variant indices
        {
            let mut ev = self.enum_variants.borrow_mut();
            ev.clear();
            for decl in &program.declarations {
                if let Decl::Enum(e) = decl {
                    let mut variant_map = std::collections::HashMap::new();
                    for (idx, variant) in e.variants.iter().enumerate() {
                        variant_map.insert(variant.name.clone(), idx);
                    }
                    ev.insert(e.name.clone(), variant_map);
                }
            }
            // Register built-in Result enum (used by ok(v)/error(e) patterns)
            let mut result_variants = std::collections::HashMap::new();
            result_variants.insert("Ok".to_string(), 0);
            result_variants.insert("Err".to_string(), 1);
            ev.insert("Result".to_string(), result_variants);
            // Register built-in Option enum (used by some(v)/none patterns)
            let mut option_variants = std::collections::HashMap::new();
            option_variants.insert("None".to_string(), 0);
            option_variants.insert("Some".to_string(), 1);
            ev.insert("Option".to_string(), option_variants);
            // Also register Result in struct_defs so ast_type_to_mir can find its fields
            let mut struct_defs = self.struct_defs.borrow_mut();
            if !struct_defs.contains_key("Result") {
                struct_defs.insert("Result".to_string(), vec![
                    ("disc".to_string(), MirType::I32),
                    ("payload".to_string(), MirType::I64),
                ]);
            }
        }

        // Pre-scan function declarations and class constructors to build a return-type map.
        // Generic functions (those with type_params) are stored as templates and
        // monomorphized lazily when concrete call sites are encountered.
        {
            let mut fn_returns = self.fn_returns.borrow_mut();
            let mut cc_map = self.class_constructor_map.borrow_mut();
            let mut method_table = self.method_table.borrow_mut();
            let mut class_parent_map = self.class_parent_map.borrow_mut();
            let mut generic_fn_templates = self.generic_function_templates.borrow_mut();
            fn_returns.clear();
            cc_map.clear();
            method_table.clear();
            class_parent_map.clear();
            generic_fn_templates.clear();
            for decl in &program.declarations {
                if let Decl::Function(f) = decl {
                    if !f.type_params.is_empty() {
                        // Generic function — store as template for lazy monomorphization
                        generic_fn_templates.insert(f.name.clone(), f.clone());
                        continue;
                    }
                    let struct_defs = self.struct_defs.borrow().clone();
                    let declared_ret = f.return_type.as_ref()
                        .map(|rt| ast_type_to_mir(rt, Some(&struct_defs)))
                        .unwrap_or(MirType::Void);
                    if f.is_async {
                        // async functions store the declared return type separately
                        self.async_fn_returns.borrow_mut().insert(f.name.clone(), declared_ret);
                        // The actual call returns a task handle (i64)
                        fn_returns.insert(f.name.clone(), MirType::I64);
                    } else {
                        fn_returns.insert(f.name.clone(), declared_ret);
                    }
                    self.function_decls.borrow_mut().insert(f.name.clone(), f.clone());
                }
                if let Decl::Class(c) = decl {
                    class_parent_map.insert(c.name.clone(), c.parent.clone());
                    if !c.type_params.is_empty() {
                        // Generic class — store methods as templates for lazy monomorphization
                        let mut class_methods = Vec::new();
                        for member in &c.members {
                            if let ClassMember::Method(m) = member {
                                let template_name = format!("{}::{}", c.name, m.name);
                                generic_fn_templates.insert(template_name, m.clone());
                                class_methods.push(m.clone());
                            }
                        }
                        self.generic_class_methods.borrow_mut().insert(c.name.clone(), class_methods);
                    }
                    if c.members.iter().any(|m| matches!(m, ClassMember::Constructor(_))) {
                        cc_map.insert(c.name.clone(), format!("{}::new", c.name));
                        for member in &c.members {
                            if let ClassMember::Constructor(_ctor) = member {
                                let defs = self.struct_defs.borrow();
                                let fields = defs.get(&c.name).cloned().unwrap_or_default();
                                fn_returns.insert(format!("{}::new", c.name), MirType::Struct(c.name.clone(), fields));
                            }
                        }
                    } else {
                        // No explicit constructor — auto-register a default one
                        cc_map.insert(c.name.clone(), format!("{}::new", c.name));
                        let defs = self.struct_defs.borrow();
                        let fields = defs.get(&c.name).cloned().unwrap_or_default();
                        fn_returns.insert(format!("{}::new", c.name), MirType::Struct(c.name.clone(), fields));
                    }
                    // Build method dispatch table for this class.
                    // Each method `fn foo()` inside `class C` becomes a free function
                    // named `C::foo` that takes `this: C` as its first parameter.
                    let mut methods: std::collections::HashMap<String, String> = std::collections::HashMap::new();
                    let mut static_set = self.static_methods.borrow_mut();
                    for member in &c.members {
                        if let ClassMember::Method(m) = member {
                            let mangled = format!("{}::{}", c.name, m.name);
                            methods.insert(m.name.clone(), mangled.clone());
                            if m.is_static {
                                static_set.insert(mangled.clone());
                            }
                            let defs = self.struct_defs.borrow();
                            let ret_type = m.return_type.as_ref()
                                .map(|rt| ast_type_to_mir(rt, Some(&defs)))
                                .unwrap_or(MirType::Void);
                            fn_returns.insert(mangled, ret_type);
                        }
                        if let ClassMember::Property(p) = member {
                            let defs = self.struct_defs.borrow();
                            let prop_type = ast_type_to_mir(&p.type_, Some(&defs));
                            if p.getter.is_some() {
                                let mangled = format!("{}::get_{}", c.name, p.name);
                                methods.insert(format!("get_{}", p.name), mangled.clone());
                                fn_returns.insert(mangled, prop_type.clone());
                            }
                            if p.setter.is_some() {
                                let mangled = format!("{}::set_{}", c.name, p.name);
                                methods.insert(format!("set_{}", p.name), mangled.clone());
                                fn_returns.insert(mangled, MirType::Void);
                            }
                        }
                    }
                    if !methods.is_empty() {
                        method_table.insert(c.name.clone(), methods);
                    }
                }
            }
        }

        let mut module = MirModule::new();

        // Collect any closure functions generated during previous lower_program calls
        {
            let cf = self.closure_functions.borrow();
            for func in cf.iter() {
                module.functions.push(func.clone());
            }
        }

        for decl in &program.declarations {
            match decl {
                Decl::Function(f) => {
                    if !f.type_params.is_empty() {
                        continue; // Generic functions are monomorphized lazily
                    }
                    if let Some(func) = self.lower_function(f) {
                        module.functions.push(func);
                    }
                }
                Decl::Class(c) => {
                    if !c.type_params.is_empty() {
                        continue; // Generic class — monomorphized lazily
                    }
                    for member in &c.members {
                        if let ClassMember::Method(m) = member {
                            if let Some(func) = self.lower_method(m, &c.name) {
                                module.functions.push(func);
                            }
                        }
                        if let ClassMember::Property(p) = member {
                            // Generate getter method: Class::get_prop(this) -> PropType
                            if let Some(getter_body) = &p.getter {
                                let getter_fn = FunctionDecl {
                                    name: format!("get_{}", p.name),
                                    type_params: vec![],
                                    params: vec![Parameter {
                                        name: "this".into(),
                                        type_: AstType::User { name: c.name.clone(), span: p.span },
                                        default: None, variadic: false, mode: ParamMode::Move, span: p.span,
                                    }],
                                    return_type: Some(p.type_.clone()),
                                    is_async: false, is_const: false, is_static: false, is_abstract: false, is_extern: false, is_test: false, is_bench: false,
                                    visibility: Visibility::Public,
                                    body: Some(getter_body.clone()),
                                    span: p.span,
                                };
                                if let Some(func) = self.lower_method(&getter_fn, &c.name) {
                                    module.functions.push(func);
                                }
                            }
                            // Generate setter method: Class::set_prop(this, value) -> void
                            if let Some((set_param, setter_body)) = &p.setter {
                                let void_type = AstType::Primitive { name: "void".into(), span: p.span };
                                let setter_fn = FunctionDecl {
                                    name: format!("set_{}", p.name),
                                    type_params: vec![],
                                    params: vec![
                                        Parameter {
                                            name: "this".into(),
                                            type_: AstType::User { name: c.name.clone(), span: p.span },
                                            default: None, variadic: false, mode: ParamMode::Move, span: p.span,
                                        },
                                        Parameter {
                                            name: set_param.clone(),
                                            type_: p.type_.clone(),
                                            default: None, variadic: false, mode: ParamMode::Move, span: p.span,
                                        },
                                    ],
                                    return_type: Some(void_type),
                                    is_async: false, is_const: false, is_static: false, is_abstract: false, is_extern: false, is_test: false, is_bench: false,
                                    visibility: Visibility::Public,
                                    body: Some(setter_body.clone()),
                                    span: p.span,
                                };
                                if let Some(func) = self.lower_method(&setter_fn, &c.name) {
                                    module.functions.push(func);
                                }
                            }
                        }
                        if let ClassMember::Constructor(ctor) = member {
                            let mut mir_func = MirFunction::new(format!("{}::new", c.name));
                            {
                                let defs = self.struct_defs.borrow();
                                mir_func.params = ctor.params.iter()
                                    .map(|p| ast_type_to_mir(&p.type_, Some(&defs)))
                                    .collect();
                                mir_func.param_modes = ctor.params.iter().map(|p| p.mode).collect();
                                mir_func.return_type = if let Some(fields) = defs.get(&c.name) {
                                    MirType::Struct(c.name.clone(), fields.clone())
                                } else {
                                    MirType::Struct(c.name.clone(), vec![])
                                };
                            }
                            let mut ctx = LowerCtx::new();
                            ctx.struct_defs = self.struct_defs.borrow().clone();
                            // Allocate `this` local for the struct being constructed
                            // so that constructor body can use `this.field = value` syntax.
                            let this_type = if let Some(fields) = ctx.struct_defs.get(&c.name) {
                                MirType::Struct(c.name.clone(), fields.clone())
                            } else {
                                MirType::Struct(c.name.clone(), vec![])
                            };
                            let this_local = ctx.alloc_local("this", this_type.clone());
         ctx.locals.insert("this".to_string(), this_local);
        ctx.locals.insert("self".to_string(), this_local);
                            // Bind constructor params to locals
                            for (i, param) in ctor.params.iter().enumerate() {
                                let local = ctx.alloc_local(&param.name, ast_type_to_mir(&param.type_, Some(&ctx.struct_defs)));
                                ctx.current_block.insts.push(MirInst::Store {
                                    dest: local,
                                    value: MirValue::Param(i),
                                });
                                ctx.locals.insert(param.name.clone(), local);
                            }
                            let last_is_tail = match ctor.body.statements.last() {
                                Some(Stmt::Expression(e)) => !matches!(e, Expr::Assignment { .. }),
                                _ => false,
                            };
                            let tail_is_field_assign = ctor.body.statements.last().map_or(false, |s| {
                                if let Stmt::Expression(e) = s {
                                    match e {
                                        Expr::Assignment { target, .. } => {
                                            if let Expr::PropertyAccess { object, .. } = target.as_ref() {
                                                if let Expr::Identifier { name, .. } = object.as_ref() {
                                                    return name == "this";
                                                }
                                            }
                                        }
                                        Expr::Binary { left, operator, .. } if matches!(operator, BinaryOp::Assign) => {
                                            if let Expr::PropertyAccess { object, .. } = left.as_ref() {
                                                if let Expr::Identifier { name, .. } = object.as_ref() {
                                                    return name == "this";
                                                }
                                            }
                                        }
                                        _ => {}
                                    }
                                }
                                false
                            });
                            for stmt in &ctor.body.statements {
                                ctx = self.lower_stmt(ctx, stmt);
                            }
                            if ctx.current_block.terminator == MirTerminator::Unreachable {
                                if last_is_tail && !tail_is_field_assign {
                                    // Return the tail expression value (e.g., StructLiteral)
                                    let val_local = ctx.next_local - 1;
                                    ctx.emit_return(MirValue::Local(val_local));
                                } else {
                                    // Load struct value from alloca before returning
                                    // (MirValue::Local(this_local) is a pointer, but return type is Struct)
                                    let val_local = ctx.alloc_local("_retval", this_type.clone());
                                    ctx.current_block.insts.push(MirInst::Load {
                                        dest: val_local,
                                        src: this_local,
                                    });
                                    ctx.emit_return(MirValue::Local(val_local));
                                }
                            }
                            mir_func.local_count = ctx.next_local;
                            mir_func.basic_blocks = ctx.blocks;
                            module.functions.push(mir_func);
                        }
                    }
                }
                _ => {}
            }
        }

        // Collect closure functions generated during this lower_program call
        {
            let cf = self.closure_functions.borrow();
            for func in cf.iter() {
                if !module.functions.iter().any(|f| f.name == func.name) {
                    module.functions.push(func.clone());
                }
            }
        }

        // Collect async wrapper functions
        {
            let af = self.async_functions.borrow();
            for func in af.iter() {
                if !module.functions.iter().any(|f| f.name == func.name) {
                    module.functions.push(func.clone());
                }
            }
        }

        // Collect specialized monomorphized functions
        {
            let sf = self.specialized_mir_functions.borrow();
            for func in sf.iter() {
                if !module.functions.iter().any(|f| f.name == func.name) {
                    module.functions.push(func.clone());
                }
            }
        }

        // Generate implicit main() if no explicit main function exists
        if !module.functions.iter().any(|f| f.name == "main" || f.name == "kyle_main") {
            let mut main_stmts: Vec<Stmt> = Vec::new();
            let pg_span = program.span.clone();
            for decl in &program.declarations {
                match decl {
                    Decl::Variable(v) => {
                        main_stmts.push(Stmt::Variable(v.clone()));
                    }
                    Decl::Expression(e) => {
                        main_stmts.push(Stmt::Expression(e.clone()));
                    }
                    _ => {}
                }
            }
            main_stmts.push(Stmt::Return(Some(Box::new(
                Expr::Literal { value: Literal::Integer(0), span: pg_span.clone() }
            ))));
            let int_type = AstType::Primitive { name: "i32".into(), span: pg_span.clone() };
            let main_fn = FunctionDecl {
                name: "main".into(),
                type_params: vec![], params: vec![],
                return_type: Some(int_type),
                is_async: false, is_const: false, is_static: false,
                is_abstract: false, is_extern: false, is_test: false, is_bench: false,
                visibility: Visibility::Public,
                body: Some(Block { statements: main_stmts, span: pg_span.clone() }),
                span: pg_span,
            };
            if let Some(mir_main) = self.lower_function(&main_fn) {
                module.functions.push(mir_main);
                // Collect closures generated during implicit main lowering
                let cf2 = self.closure_functions.borrow();
                for func in cf2.iter() {
                    if !module.functions.iter().any(|f| f.name == func.name) {
                        module.functions.push(func.clone());
                    }
                }
            }
        }

        module.links = program.links.clone();
        module
    }

}
