use crate::ast::*;
use std::sync::atomic::{AtomicUsize, Ordering};

static EL_COUNTER: AtomicUsize = AtomicUsize::new(0);

fn fresh_el() -> String {
    let id = EL_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("_el{}", id)
}

/// Generate JavaScript code from a KyxFile AST.
pub fn generate(file: &KyxFile) -> String {
    let mut js = String::new();
    js.push_str("// Generated by Kyle UI Compiler\n");
    js.push_str("// Target: Web (JS/DOM)\n\n");

    // Include reactivity and router runtimes
    js.push_str("const { ReactiveState, Binding, createKyleEvent } = require('./reactivity.js');\n");
    js.push_str("const { Router, routeParams } = require('./router.js');\n");
    js.push_str("const { A11yManager } = require('./a11y.js');\n");
    js.push_str("const { portalManager } = require('./portal.js');\n");
    js.push_str("const { ErrorBoundary } = require('./error_boundary.js');\n");
    js.push_str("const { getI18n, t, setLocale } = require('./i18n.js');\n");
    js.push_str("const _i18n = getI18n();\n");
    js.push_str("const _a11y = new A11yManager();\n\n");

    // Generate styles
    let style_js = crate::style_gen::generate_styles(&file.styles);
    js.push_str(&style_js);

    // Generate animations
    let anim_js = crate::anim_gen::generate_animations(&file.animations);
    js.push_str(&anim_js);

    // Determine component name from first route
    let comp_name = if let Some(route) = file.routes.first() {
        let name = route.path.trim_start_matches('/').replace('/', "_").replace(&['{', '}', '-'][..], "");
        if name.is_empty() { "home".to_string() } else { name }
    } else {
        "component".to_string()
    };

    // Generate component function
    js.push_str(&format!("function render{}(container, initialState = {{}}) {{\n", comp_name));
    js.push_str("  const state = new ReactiveState(initialState);\n");
    js.push_str("  const el = document.createDocumentFragment();\n");

    for node in &file.body {
        gen_node(node, &mut js, 2, "el");
    }

    js.push_str("  return { element: el, state };\n");
    js.push_str("}\n\n");

    // Route registration from routes
    if !file.routes.is_empty() {
        js.push_str("// Register routes\n");
        js.push_str("if (typeof window !== 'undefined') {\n");
        js.push_str("  if (!window.__KYLE_ROUTES) window.__KYLE_ROUTES = {};\n");
        for route in &file.routes {
            js.push_str(&format!("  window.__KYLE_ROUTES[{:?}] = render{};\n", route.path, comp_name));
        }
        js.push_str("}\n\n");
    }

    // Export
    js.push_str("if (typeof module !== 'undefined' && module.exports) {\n");
    js.push_str(&format!("  module.exports = {{ render: render{}, styles, animations }};\n", comp_name));
    js.push_str("}\n");

    js
}

fn gen_node(node: &KyxNode, js: &mut String, indent: usize, parent: &str) {
    let el = fresh_el();
    let ind = " ".repeat(indent);
    let ind2 = " ".repeat(indent + 2);

    match node {
        KyxNode::Element { tag, attrs, children } => {
            let tag_js = js_tag(tag);
            if tag == "portal" {
                let mut target = "body";
                for a in attrs {
                    if a.name == "target" {
                        if let AttrValue::String(ref v) = a.value { target = v; }
                    }
                }
                js.push_str(&format!("{}// Portal: render to '{}'\n", ind, target));
                for child in children {
                    gen_node(child, js, indent, &format!("{}_content", el));
                }
                js.push_str(&format!("{}if (typeof {}_content !== 'undefined') {{\n", ind, el));
                js.push_str(&format!("{}  portalManager.create({}_content, {:?});\n", ind, el, target));
                js.push_str(&format!("{}}}\n", ind));
                return;
            }
            if tag == "error_boundary" {
                let b = fresh_el();
                js.push_str(&format!("{}// Error boundary\n", ind));
                js.push_str(&format!("{}const {} = new ErrorBoundary();\n", ind, b));
                js.push_str(&format!("{}const {}_wrap = {}.wrap(() => {{\n", ind, b, b));
                js.push_str(&format!("{}  const {}_c = document.createDocumentFragment();\n", ind, b));
                for child in children {
                    gen_node(child, js, indent + 2, &format!("{}_c", b));
                }
                js.push_str(&format!("{}  return {}_c;\n", ind, b));
                js.push_str(&format!("{}}});\n", ind));
                js.push_str(&format!("{}const {}_r = {}_wrap();\n", ind, b, b));
                js.push_str(&format!("{}if ({}_r) {{ {}.appendChild({}_r); }}\n", ind, b, parent, b));
                return;
            }
            if tag == "outlet" {
                let mut name = "default";
                for a in attrs {
                    if a.name == "name" {
                        if let AttrValue::String(ref v) = a.value { name = v; }
                    }
                }
                js.push_str(&format!("{}// Outlet: '{}'\n", ind, name));
                js.push_str(&format!("{}portalManager.registerOutlet({:?}, {});\n", ind, name, el));
            }
            js.push_str(&format!("{}const {} = document.createElement('{}');\n", ind, el, tag_js));
            gen_attrs(attrs, js, indent, &el);
            gen_events(attrs, js, indent, &el);
            js.push_str(&format!("{}A11yManager.applyAria({}, {:?});\n", ind, el, tag));
            for child in children {
                gen_node(child, js, indent + 2, &el);
            }
            js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, el));
        }
        KyxNode::SelfClosing { tag, attrs } => {
            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const {} = document.createElement('{}');\n", ind, el, tag_js));
            gen_attrs(attrs, js, indent, &el);
            gen_events(attrs, js, indent, &el);
            js.push_str(&format!("{}A11yManager.applyAria({}, {:?});\n", ind, el, tag));
            js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, el));
        }
        KyxNode::Slot { name, fallback } => {
            js.push_str(&format!("{}// Slot: {}\n", ind, name));
            if !fallback.is_empty() {
                for child in fallback {
                    gen_node(child, js, indent, parent);
                }
            }
        }
        KyxNode::If { condition, then_branch, else_branch } => {
            js.push_str(&format!("{}if ({}) {{\n", ind, condition));
            for child in then_branch {
                gen_node(child, js, indent + 4, parent);
            }
            if !else_branch.is_empty() {
                js.push_str(&format!("{}}} else {{\n", ind));
                for child in else_branch {
                    gen_node(child, js, indent + 4, parent);
                }
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::For { item, list, body } => {
            js.push_str(&format!("{}for (const {} of {}) {{\n", ind, item, list));
            for child in body {
                gen_node(child, js, indent + 4, parent);
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::Match { expr, cases } => {
            js.push_str(&format!("{}switch ({}) {{\n", ind, expr));
            for case in cases {
                js.push_str(&format!("{}  case {}:\n", ind, case.pattern));
                for child in &case.body {
                    gen_node(child, js, indent + 8, parent);
                }
                js.push_str(&format!("{}    break;\n", ind));
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        KyxNode::Expr(e) => {
            js.push_str(&format!("{}// Expression: {}\n", ind, e));
            js.push_str(&format!("{}{}\n", ind, e));
        }
        KyxNode::CodeBlock(_code) => {
            // Code blocks are handled at file level — skip in body
        }
        KyxNode::Text(text) => {
            js.push_str(&format!("{}{}.appendChild(document.createTextNode({:?}));\n", ind, parent, text));
        }
    }
}

fn gen_attrs(attrs: &[KyxAttr], js: &mut String, indent: usize, el: &str) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        match &attr.value {
            AttrValue::String(val) => {
                match attr.name.as_str() {
                    "tpl" | "style" => {
                        js.push_str(&format!("{}applyStyle({}, {:?});\n", ind, el, val));
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation({}, {:?});\n", ind, el, val));
                    }
                    "text" | "value" | "label" => {
                        js.push_str(&format!("{}{}.textContent = {:?};\n", ind, el, val));
                    }
                    "class" | "id" => {
                        js.push_str(&format!("{}{}.setAttribute({:?}, {:?});\n", ind, el, attr.name, val));
                    }
                    _ => {
                        js.push_str(&format!("{}{}.setAttribute({:?}, {:?});\n", ind, el, attr.name, val));
                    }
                }
            }
            AttrValue::Expr(expr) => {
                match attr.name.as_str() {
                    "bind" => {
                        js.push_str(&format!("{}Binding.twoWay({}, state, {:?}, 'input');\n", ind, el, expr));
                    }
                    "text" | "value" => {
                        js.push_str(&format!("{}Binding.oneWay({}, 'textContent', state, {:?});\n", ind, el, expr));
                    }
                    "tpl" => {
                        js.push_str(&format!("{}applyStyle({}, state.get({:?}));\n", ind, el, expr));
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation({}, state.get({:?}));\n", ind, el, expr));
                    }
                    "checked" => {
                        js.push_str(&format!("{}Binding.oneWay({}, 'checked', state, {:?});\n", ind, el, expr));
                    }
                    "disabled" => {
                        js.push_str(&format!("{}Binding.oneWay({}, 'disabled', state, {:?});\n", ind, el, expr));
                    }
                    "click" | "change" | "input" | "mouse_enter" | "mouse_leave"
                    | "focus" | "blur" | "keydown" | "keyup" | "submit" | "scroll"
                    | "dblclick" | "context_menu" | "mouse_down" | "mouse_up"
                    | "mouse_move" | "touch_start" | "touch_end" | "touch_move" => {}
                    _ => {
                        js.push_str(&format!("{}{}.setAttribute({:?}, state.get({:?}));\n", ind, el, attr.name, expr));
                    }
                }
            }
            AttrValue::Flag => {
                js.push_str(&format!("{}{}.setAttribute({:?}, '');\n", ind, el, attr.name));
            }
        }
    }
}

fn gen_events(attrs: &[KyxAttr], js: &mut String, indent: usize, el: &str) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        let event_name = match attr.name.as_str() {
            "click" => "click",
            "change" => "change",
            "input" => "input",
            "mouse_enter" => "mouseenter",
            "mouse_leave" => "mouseleave",
            "focus" => "focus",
            "blur" => "blur",
            "keydown" => "keydown",
            "keyup" => "keyup",
            "submit" => "submit",
            "scroll" => "scroll",
            "dblclick" => "dblclick",
            "context_menu" => "contextmenu",
            "mouse_down" => "mousedown",
            "mouse_up" => "mouseup",
            "mouse_move" => "mousemove",
            "touch_start" => "touchstart",
            "touch_end" => "touchend",
            "touch_move" => "touchmove",
            _ => continue,
        };
        if let AttrValue::Expr(handler) = &attr.value {
            js.push_str(&format!("{}{}.addEventListener({:?}, (e) => {{ {}(createKyleEvent(e)); }});\n", ind, el, event_name, handler));
        }
    }
}

fn js_tag(tag: &str) -> &str {
    match tag.to_lowercase().as_str() {
        "view" | "column" | "row" | "stack" | "container" => "div",
        "text" | "label" => "span",
        "button" | "iconbutton" => "button",
        "textfield" => "input",
        "passwordfield" => "input",
        "textarea" => "textarea",
        "checkbox" => "input",
        "radio" => "input",
        "image" | "icon" => "img",
        "link" => "a",
        "list" => "ul",
        "form" => "form",
        "dialog" => "dialog",
        "canvas" => "canvas",
        "video" => "video",
        "audio" => "audio",
        "select" => "select",
        "slider" => "input",
        "switch" => "input",
        "progress" => "progress",
        "spinner" => "div",
        _ => "div",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    #[test]
    fn test_generate_simple() {
        let source = r#"<text value="Hello" />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("createElement"));
        assert!(js.contains("Hello"));
    }

    #[test]
    fn test_generate_with_events() {
        let source = r#"<button text="Click" click=@handle_click />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("addEventListener"));
        assert!(js.contains("createKyleEvent"));
    }

    #[test]
    fn test_generate_with_binding() {
        let source = r#"<text_field bind=@email />"#;
        let file = parser::parse(source).unwrap();
        let js = generate(&file);
        assert!(js.contains("Binding.twoWay"));
    }
}
