// kyc_frontend::lexer — KL source code tokenizer
//
// Transforms KL source text into a sequence of tokens.
// Handles indentation-based block detection (INDENT/DEDENT tokens).
// Reference: docs/02-formal-grammar.md

use kyc_core::span::{Position, Span};
use crate::token::{Token, TokenKind};

/// The KL lexer.
pub struct Lexer {
    source: String,
    chars: Vec<char>,
    pos: usize,
    line: usize,
    column: usize,
    indent_stack: Vec<usize>,
    pending_tokens: Vec<Token>,
    at_bol: bool,
}

impl Lexer {
    /// Create a new lexer for the given source text.
    pub fn new(source: &str) -> Self {
        let chars: Vec<char> = source.chars().collect();
        Self {
            source: source.to_string(),
            chars,
            pos: 0,
            line: 1,
            column: 1,
            indent_stack: vec![0],
            pending_tokens: Vec::new(),
            at_bol: true,
        }
    }

    /// Tokenize the entire source and return all tokens with INDENT/DEDENT.
    pub fn tokenize(&mut self) -> Vec<Token> {
        let mut tokens = Vec::new();
        loop {
            match self.next_token() {
                Some(tok) => {
                    let is_eof = matches!(tok.kind, TokenKind::Eof);
                    tokens.push(tok);
                    if is_eof {
                        break;
                    }
                }
                None => break,
            }
        }
        tokens
    }

    /// Advance to the next token.
    fn next_token(&mut self) -> Option<Token> {
        // Drain any pending tokens (generated by indentation handling).
        if !self.pending_tokens.is_empty() {
            return Some(self.pending_tokens.remove(0));
        }

        self.skip_whitespace_and_comments();

        if self.pos >= self.chars.len() {
            // Emit DEDENTs for remaining indentation levels.
            let start_pos = Position { line: self.line, column: self.column, offset: self.pos };
            let remaining = self.indent_stack.len() - 1;
            if remaining > 0 {
                self.indent_stack.truncate(1);
                return Some(self.make_token(TokenKind::Dedent, &start_pos));
            }
            return Some(self.make_token(TokenKind::Eof, &start_pos));
        }

        let c = self.chars[self.pos];
        let start_pos = Position { line: self.line, column: self.column, offset: self.pos };
        // Detect newline.
        if c == '\n' {
            self.advance();
            self.handle_newline();
            return Some(self.make_token(TokenKind::Newline, &start_pos));
        }

        self.at_bol = false;

        // Single-character tokens.
        if let Some(kind) = match c {
            '+' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::PlusEquals) }
                else if self.current() == '%' { self.advance(); Some(TokenKind::PlusPercent) }
                else { Some(TokenKind::Plus) }
            }
            '-' => {
                self.advance();
                if self.current() == '>' { self.advance(); Some(TokenKind::Arrow) }
                else if self.current() == '=' { self.advance(); Some(TokenKind::MinusEquals) }
                else if self.current() == '%' { self.advance(); Some(TokenKind::MinusPercent) }
                else { Some(TokenKind::Minus) }
            }
            '*' => {
                self.advance();
                if self.current() == '*' { self.advance(); Some(TokenKind::StarStar) }
                else if self.current() == '=' { self.advance(); Some(TokenKind::StarEquals) }
                else if self.current() == '%' { self.advance(); Some(TokenKind::StarPercent) }
                else { Some(TokenKind::Star) }
            }
            '/' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::SlashEquals) }
                else { Some(TokenKind::Slash) }
            }
            '%' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::PercentEquals) }
                else { Some(TokenKind::Percent) }
            }
            '=' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::EqualsEquals) }
                else if self.current() == '>' { self.advance(); Some(TokenKind::FatArrow) }
                else { Some(TokenKind::Equals) }
            }
            '!' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::BangEquals) }
                else { Some(TokenKind::Bang) }
            }
            '<' => {
                self.advance();
                if self.current() == '<' {
                    self.advance();
                    if self.current() == '=' { self.advance(); Some(TokenKind::LessLessEquals) }
                    else { Some(TokenKind::LessLess) }
                } else if self.current() == '=' { self.advance(); Some(TokenKind::LessEquals) }
                else { Some(TokenKind::Less) }
            }
            '>' => {
                self.advance();
                if self.current() == '>' {
                    self.advance();
                    if self.current() == '=' { self.advance(); Some(TokenKind::GreaterGreaterEquals) }
                    else { Some(TokenKind::GreaterGreater) }
                } else if self.current() == '=' { self.advance(); Some(TokenKind::GreaterEquals) }
                else { Some(TokenKind::Greater) }
            }
            '&' => {
                self.advance();
                if self.current() == '&' { self.advance(); Some(TokenKind::And) }
                else if self.current() == '=' { self.advance(); Some(TokenKind::AmpersandEquals) }
                else { Some(TokenKind::Ampersand) }
            }
            '|' => {
                self.advance();
                if self.current() == '|' { self.advance(); Some(TokenKind::Or) }
                else if self.current() == '=' { self.advance(); Some(TokenKind::PipeEquals) }
                else { Some(TokenKind::Pipe) }
            }
            '^' => {
                self.advance();
                if self.current() == '=' { self.advance(); Some(TokenKind::CaretEquals) }
                else { Some(TokenKind::Caret) }
            }
            '~' => { self.advance(); Some(TokenKind::Tilde) }
            '.' => {
                self.advance();
                if self.current() == '.' {
                    self.advance();
                    if self.current() == '.' {
                        self.advance();
                        Some(TokenKind::DotDotDot)
                    } else if self.current() == '=' {
                        self.advance();
                        Some(TokenKind::DotDotEquals)
                    } else if self.current() == '<' {
                        self.advance();
                        Some(TokenKind::DotDotLess)
                    } else {
                        Some(TokenKind::DotDot)
                    }
                } else {
                    Some(TokenKind::Dot)
                }
            }
            ',' => { self.advance(); Some(TokenKind::Comma) }
            ';' => { self.advance(); Some(TokenKind::Semicolon) }
            ':' => {
                self.advance();
                if self.current() == '=' {
                    self.advance();
                    Some(TokenKind::Walrus)   // := — now used for constants
                } else {
                    Some(TokenKind::Colon)
                }
                // Note: `::` inheritance is handled by the parser (two consecutive Colons)
            }
            '?' => {
                self.advance();
                if self.current() == '?' { self.advance(); Some(TokenKind::QuestionQuestion) }
                else if self.current() == '.' { self.advance(); Some(TokenKind::QuestionDot) }
                else { Some(TokenKind::Question) }
            }
            '(' => { self.advance(); Some(TokenKind::LParen) }
            ')' => { self.advance(); Some(TokenKind::RParen) }
            '[' => { self.advance(); Some(TokenKind::LBracket) }
            ']' => { self.advance(); Some(TokenKind::RBracket) }
            '{' => { self.advance(); Some(TokenKind::LBrace) }
            '}' => { self.advance(); Some(TokenKind::RBrace) }
            '@' => { self.advance(); Some(TokenKind::At) }
            '#' => {
                // `skip_whitespace_and_comments` leaves `#[` alone for attribute syntax
                self.advance();
                Some(TokenKind::Hash)
            }
            _ => None,
        } {
            return Some(self.make_token(kind, &start_pos));
        }

        // Raw string: r"..." — no escape processing (must be BEFORE identifier lexing)
        if c == 'r' && self.peek() == '"' {
            self.advance(); // consume 'r'
            return Some(self.lex_string_raw());
        }

        // Identifiers, keywords, types.
        if c.is_alphabetic() || c == '_' {
            let start = self.pos;
            while self.pos < self.chars.len()
                && (self.chars[self.pos].is_alphanumeric() || self.chars[self.pos] == '_')
            {
                self.advance();
            }
            let word: String = self.chars[start..self.pos].iter().collect();
            let kind = self.keyword_or_identifier(&word);
            return Some(self.make_token(kind, &start_pos));
        }

        // Numbers.
        if c.is_ascii_digit() {
            return Some(self.lex_number());
        }

        // Strings.
        if c == '"' {
            return Some(self.lex_string());
        }

        // Chars.
        if c == '\'' {
            return Some(self.lex_char());
        }

        // Unknown character.
        let ch = c;
        self.advance();
        Some(self.make_token(TokenKind::LexError(format!("unexpected character: '{}'", ch)), &start_pos))
    }

    /// Determine if a word is a keyword, type name, or plain identifier.
    fn keyword_or_identifier(&self, word: &str) -> TokenKind {
        match word {
            "fn" => TokenKind::Fn,
            "class" => TokenKind::Class,
            "abstract" => TokenKind::Abstract,
            "abs" => TokenKind::Abstract,     // temporary alias for compat
            "final" => TokenKind::Final,
            "struct" => TokenKind::Struct,    // temporary alias for final class
            "enum" => TokenKind::Enum,
            "contract" => TokenKind::Contract,
            "if" => TokenKind::If,
            "elif" => TokenKind::Elif,
            "else" => TokenKind::Else,
            "while" => TokenKind::While,
            "for" => TokenKind::For,
            "in" => TokenKind::In,
            "match" => TokenKind::Match,
            "return" => TokenKind::Return,
            "break" => TokenKind::Break,
            "continue" => TokenKind::Continue,
            "defer" => TokenKind::Defer,
            "guard" => TokenKind::Guard,
            "unsafe" => TokenKind::Unsafe,
            "async" => TokenKind::Async,
            "await" => TokenKind::Await,
            "const" => TokenKind::Const,
            "loop" => TokenKind::Loop,
            "type" => TokenKind::Type,
            "true" => TokenKind::True,
            "false" => TokenKind::False,
            "none" => TokenKind::None,
            "ok" => TokenKind::OkKw,
            "extern" => TokenKind::Extern,
            "use" => TokenKind::Use,
            "import" => TokenKind::Import,
            "from" => TokenKind::From,
            "as" => TokenKind::As,
            "get" => TokenKind::Get,
            "set" => TokenKind::Set,
            "static" => TokenKind::Static,
            "implements" => TokenKind::Implements,
            "and" => TokenKind::And,
            "or" => TokenKind::Or,
            "not" => TokenKind::Bang,
            "is" => TokenKind::Is,
            "super" => TokenKind::Super,
            "null" => TokenKind::Null,
            _ => TokenKind::Identifier(word.to_string()),
        }
    }

    fn lex_number(&mut self) -> Token {
        let start = self.pos;
        let start_pos = Position { line: self.line, column: self.column, offset: self.pos };
        let mut is_float = false;

        // Handle hex: 0x...
        if self.chars[start] == '0' && self.peek() == 'x' {
            self.advance();
            self.advance();
            while self.pos < self.chars.len()
                && self.chars[self.pos].is_ascii_hexdigit()
            {
                self.advance();
            }
            let value: String = self.chars[start..self.pos].iter().collect();
            return self.make_token(TokenKind::Integer(value), &start_pos);
        }

        // Handle binary: 0b...
        if self.chars[start] == '0' && self.peek() == 'b' {
            self.advance();
            self.advance();
            while self.pos < self.chars.len()
                && (self.chars[self.pos] == '0' || self.chars[self.pos] == '1')
            {
                self.advance();
            }
            let value: String = self.chars[start..self.pos].iter().collect();
            return self.make_token(TokenKind::Integer(value), &start_pos);
        }

        // Decimal digits.
        while self.pos < self.chars.len() && self.chars[self.pos].is_ascii_digit() {
            self.advance();
        }

        // Float: dot followed by digit.
        if self.pos < self.chars.len() && self.chars[self.pos] == '.' {
            let next = self.chars.get(self.pos + 1).copied();
            if next.is_some_and(|c| c.is_ascii_digit()) {
                is_float = true;
                self.advance(); // consume '.'
                while self.pos < self.chars.len() && self.chars[self.pos].is_ascii_digit() {
                    self.advance();
                }
            }
        }

        let value: String = self.chars[start..self.pos].iter().collect();
        if is_float {
            self.make_token(TokenKind::Float(value), &start_pos)
        } else {
            self.make_token(TokenKind::Integer(value), &start_pos)
        }
    }

    fn lex_string(&mut self) -> Token {
        let start_pos = Position { line: self.line, column: self.column, offset: self.pos };
        self.advance(); // consume opening "
        let mut value = String::new();
        while self.pos < self.chars.len() && self.chars[self.pos] != '"' {
            if self.chars[self.pos] == '\\' {
                self.advance();
                if self.pos < self.chars.len() {
                    let ch = self.chars[self.pos];
                    self.advance();
                    match ch {
                        'n' => value.push('\n'),
                        't' => value.push('\t'),
                        'r' => value.push('\r'),
                        '\\' => value.push('\\'),
                        '"' => value.push('"'),
                        _ => { value.push('\\'); value.push(ch); }
                    }
                }
            } else {
                value.push(self.chars[self.pos]);
                self.advance();
            }
        }
        if self.pos < self.chars.len() {
            self.advance(); // consume closing "
        }
        self.make_token(TokenKind::String(value), &start_pos)
    }

    /// Lex a raw string literal `r"..."`. No escape sequences are processed.
    fn lex_string_raw(&mut self) -> Token {
        let start_pos = Position { line: self.line, column: self.column, offset: self.pos };
        // The opening 'r' has already been consumed by the caller.
        self.advance(); // consume opening "
        let mut value = String::new();
        while self.pos < self.chars.len() && self.chars[self.pos] != '"' {
            value.push(self.chars[self.pos]);
            self.advance();
        }
        if self.pos < self.chars.len() {
            self.advance(); // consume closing "
        }
        self.make_token(TokenKind::String(value), &start_pos)
    }

    fn lex_char(&mut self) -> Token {
        let start_pos = Position { line: self.line, column: self.column, offset: self.pos };
        self.advance(); // consume opening '
        let value = if self.chars[self.pos] == '\\' {
            self.advance();
            let ch = self.chars[self.pos];
            self.advance();
            match ch {
                'n' => '\n',
                't' => '\t',
                '\\' => '\\',
                '\'' => '\'',
                _ => ch,
            }
        } else {
            let ch = self.chars[self.pos];
            self.advance();
            ch
        };
        if self.pos < self.chars.len() && self.chars[self.pos] == '\'' {
            self.advance(); // consume closing '
        }
        self.make_token(TokenKind::Char(value.to_string()), &start_pos)
    }

    // -----------------------------------------------------------------------
    // Indentation handling
    // -----------------------------------------------------------------------

    fn handle_newline(&mut self) {
        self.at_bol = true;
        let indent = self.measure_indent();
        let last = *self.indent_stack.last().unwrap_or(&0);
        let pos = Position { line: self.line, column: self.column, offset: self.pos };

        if indent > last {
            self.indent_stack.push(indent);
            self.pending_tokens.push(self.make_token(TokenKind::Indent, &pos));
        } else if indent < last {
            while let Some(&level) = self.indent_stack.last() {
                if level <= indent {
                    break;
                }
                self.indent_stack.pop();
                self.pending_tokens.push(self.make_token(TokenKind::Dedent, &pos));
            }
        }
    }

    fn measure_indent(&mut self) -> usize {
        let mut count = 0;
        let mut i = self.pos;
        while i < self.chars.len() {
            match self.chars[i] {
                ' ' => {
                    count += 1;
                    i += 1;
                }
                '\t' => {
                    count += 4;
                    i += 1;
                }
                '\n' | '\r' => {
                    // Blank line — reset and keep reading.
                    count = 0;
                    i += 1;
                }
                '#' => {
                    // Comment — skip to end of line.
                    while i < self.chars.len() && self.chars[i] != '\n' {
                        i += 1;
                    }
                    count = 0;
                    i += 1;
                }
                _ => break,
            }
        }
        // Do NOT advance the main position — measure_indent is a lookahead.
        // The main lexer position is advanced by skip_whitespace_and_comments.
        count
    }

    // -----------------------------------------------------------------------
    // Utility helpers
    // -----------------------------------------------------------------------

    fn skip_whitespace_and_comments(&mut self) {
        while self.pos < self.chars.len() {
            match self.chars[self.pos] {
                ' ' | '\t' | '\r' => {
                    self.advance();
                }
                '#' => {
                    // Check for doc comment `##`
                    let is_doc = self.pos + 1 < self.chars.len() && self.chars[self.pos + 1] == '#';
                    if is_doc {
                        self.advance(); // skip first #
                    }
                    // Check for attribute start `#[` (not a comment)
                    if !is_doc && self.pos + 1 < self.chars.len() && self.chars[self.pos + 1] == '[' {
                        break; // leave `#` for the main tokenizer
                    }
                    // Line comment: skip to newline.
                    while self.pos < self.chars.len() && self.chars[self.pos] != '\n' {
                        self.advance();
                    }
                }
                _ => break,
            }
        }
    }

    fn advance(&mut self) {
        if self.pos < self.chars.len() {
            if self.chars[self.pos] == '\n' {
                self.line += 1;
                self.column = 1;
            } else {
                self.column += 1;
            }
            self.pos += 1;
        }
    }

    fn peek(&self) -> char {
        self.chars.get(self.pos + 1).copied().unwrap_or('\0')
    }

    /// Return the character at the current position, or NUL if at end.
    fn current(&self) -> char {
        self.chars.get(self.pos).copied().unwrap_or('\0')
    }

    fn make_token(&self, kind: TokenKind, start_pos: &Position) -> Token {
        let end = Position {
            line: self.line,
            column: self.column,
            offset: self.pos,
        };
        let span = Span {
            start: *start_pos,
            end,
            file_id: 0,
        };
        Token::new(kind, span)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tokenize(source: &str) -> Vec<TokenKind> {
        let mut lexer = Lexer::new(source);
        lexer.tokenize().into_iter().map(|t| t.kind).collect()
    }

    // -----------------------------------------------------------------------
    // Literals
    // -----------------------------------------------------------------------

    #[test]
    fn test_integer() {
        let kinds = tokenize("42");
        assert_eq!(kinds, vec![TokenKind::Integer("42".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_hex_integer() {
        let kinds = tokenize("0xFF");
        assert_eq!(kinds, vec![TokenKind::Integer("0xFF".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_binary_integer() {
        let kinds = tokenize("0b1010");
        assert_eq!(kinds, vec![TokenKind::Integer("0b1010".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_float() {
        let kinds = tokenize("3.14");
        assert_eq!(kinds, vec![TokenKind::Float("3.14".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_string() {
        let kinds = tokenize(r#""hello""#);
        assert_eq!(kinds, vec![TokenKind::String("hello".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_string_with_escape() {
        let kinds = tokenize(r#""hello\nworld""#);
        assert_eq!(kinds, vec![TokenKind::String("hello\nworld".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_string_tab_escape() {
        let kinds = tokenize(r#""col1\tcol2""#);
        assert_eq!(kinds, vec![TokenKind::String("col1\tcol2".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_string_quote_escape() {
        let kinds = tokenize(r#""she said \"hello\"""#);
        assert_eq!(kinds, vec![TokenKind::String("she said \"hello\"".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_char() {
        let kinds = tokenize("'x'");
        assert_eq!(kinds, vec![TokenKind::Char("x".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_char_escape() {
        let kinds = tokenize(r"'\n'");
        assert_eq!(kinds, vec![TokenKind::Char("\n".into()), TokenKind::Eof]);
    }

    #[test]
    fn test_boolean() {
        let kinds = tokenize("true false");
        assert_eq!(kinds, vec![TokenKind::True, TokenKind::False, TokenKind::Eof]);
    }

    // -----------------------------------------------------------------------
    // Keywords
    // -----------------------------------------------------------------------

    #[test]
    fn test_keywords() {
        let kinds = tokenize("fn class abstract final struct enum contract if elif else while for in match return break defer guard unsafe async await const loop type none ok error extern");
        assert_eq!(kinds, vec![
            TokenKind::Fn, TokenKind::Class, TokenKind::Abstract, TokenKind::Final, TokenKind::Struct,
            TokenKind::Enum, TokenKind::Contract, TokenKind::If, TokenKind::Elif,
            TokenKind::Else, TokenKind::While, TokenKind::For, TokenKind::In,
            TokenKind::Match, TokenKind::Return, TokenKind::Break, TokenKind::Defer,
            TokenKind::Guard, TokenKind::Unsafe, TokenKind::Async, TokenKind::Await,
            TokenKind::Const, TokenKind::Loop, TokenKind::Type, TokenKind::None,
            TokenKind::OkKw, TokenKind::Identifier("error".to_string()), TokenKind::Extern,
            TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_import_as_keywords() {
        let kinds = tokenize("import as");
        assert_eq!(kinds, vec![
            TokenKind::Import, TokenKind::As, TokenKind::Eof,
        ]);
    }

    // -----------------------------------------------------------------------
    // Identifiers
    // -----------------------------------------------------------------------

    #[test]
    fn test_identifier() {
        let kinds = tokenize("hello world");
        assert_eq!(kinds, vec![
            TokenKind::Identifier("hello".into()),
            TokenKind::Identifier("world".into()),
            TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_underscore_identifier() {
        let kinds = tokenize("_private __private");
        assert_eq!(kinds, vec![
            TokenKind::Identifier("_private".into()),
            TokenKind::Identifier("__private".into()),
            TokenKind::Eof,
        ]);
    }

    // -----------------------------------------------------------------------
    // Single-char operators
    // -----------------------------------------------------------------------

    #[test]
    fn test_arithmetic_operators() {
        let kinds = tokenize("+ - * / %");
        assert_eq!(kinds, vec![
            TokenKind::Plus, TokenKind::Minus, TokenKind::Star,
            TokenKind::Slash, TokenKind::Percent, TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_comparison_operators() {
        let kinds = tokenize("< >");
        assert_eq!(kinds, vec![
            TokenKind::Less, TokenKind::Greater, TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_bitwise_operators() {
        let kinds = tokenize("& | ^ ~");
        assert_eq!(kinds, vec![
            TokenKind::Ampersand, TokenKind::Pipe,
            TokenKind::Caret, TokenKind::Tilde,
            TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_delimiters() {
        let kinds = tokenize("( ) [ ] { } , . :");
        assert_eq!(kinds, vec![
            TokenKind::LParen, TokenKind::RParen,
            TokenKind::LBracket, TokenKind::RBracket,
            TokenKind::LBrace, TokenKind::RBrace,
            TokenKind::Comma, TokenKind::Dot, TokenKind::Colon,
            TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_bang() {
        let kinds = tokenize("!");
        assert_eq!(kinds, vec![TokenKind::Bang, TokenKind::Eof]);
    }

    #[test]
    fn test_question() {
        let kinds = tokenize("?");
        assert_eq!(kinds, vec![TokenKind::Question, TokenKind::Eof]);
    }

    // -----------------------------------------------------------------------
    // Multi-char operators
    // -----------------------------------------------------------------------

    #[test]
    fn test_arrow() {
        let kinds = tokenize("->");
        assert_eq!(kinds, vec![TokenKind::Arrow, TokenKind::Eof]);
    }

    #[test]
    fn test_fat_arrow() {
        let kinds = tokenize("=>");
        assert_eq!(kinds, vec![TokenKind::FatArrow, TokenKind::Eof]);
    }

    #[test]
    fn test_equals_equals() {
        let kinds = tokenize("==");
        assert_eq!(kinds, vec![TokenKind::EqualsEquals, TokenKind::Eof]);
    }

    #[test]
    fn test_not_equals() {
        let kinds = tokenize("!=");
        assert_eq!(kinds, vec![TokenKind::BangEquals, TokenKind::Eof]);
    }

    #[test]
    fn test_less_equals() {
        let kinds = tokenize("<=");
        assert_eq!(kinds, vec![TokenKind::LessEquals, TokenKind::Eof]);
    }

    #[test]
    fn test_greater_equals() {
        let kinds = tokenize(">=");
        assert_eq!(kinds, vec![TokenKind::GreaterEquals, TokenKind::Eof]);
    }

    #[test]
    fn test_logical_and_or() {
        let kinds = tokenize("&& ||");
        assert_eq!(kinds, vec![TokenKind::And, TokenKind::Or, TokenKind::Eof]);
    }

    #[test]
    fn test_shift() {
        let kinds = tokenize("<< >>");
        assert_eq!(kinds, vec![TokenKind::LessLess, TokenKind::GreaterGreater, TokenKind::Eof]);
    }

    #[test]
    fn test_shift_assign() {
        let kinds = tokenize("<<= >>=");
        assert_eq!(kinds, vec![TokenKind::LessLessEquals, TokenKind::GreaterGreaterEquals, TokenKind::Eof]);
    }

    #[test]
    fn test_compound_assign() {
        let kinds = tokenize("+= -= *= /= %= &= |= ^=");
        assert_eq!(kinds, vec![
            TokenKind::PlusEquals, TokenKind::MinusEquals, TokenKind::StarEquals,
            TokenKind::SlashEquals, TokenKind::PercentEquals,
            TokenKind::AmpersandEquals, TokenKind::PipeEquals, TokenKind::CaretEquals,
            TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_wrapping_arithmetic() {
        let kinds = tokenize("+% -% *%");
        assert_eq!(kinds, vec![
            TokenKind::PlusPercent, TokenKind::MinusPercent, TokenKind::StarPercent,
            TokenKind::Eof,
        ]);
    }

    #[test]
    fn test_question_dot() {
        let kinds = tokenize("?.");
        assert_eq!(kinds, vec![TokenKind::QuestionDot, TokenKind::Eof]);
    }

    #[test]
    fn test_range_operator() {
        let kinds = tokenize("..");
        assert_eq!(kinds, vec![TokenKind::DotDot, TokenKind::Eof]);
    }

    #[test]
    fn test_spread_operator() {
        let kinds = tokenize("...");
        assert_eq!(kinds, vec![TokenKind::DotDotDot, TokenKind::Eof]);
    }

    #[test]
    fn test_equals_assign() {
        let kinds = tokenize("=");
        assert_eq!(kinds, vec![TokenKind::Equals, TokenKind::Eof]);
    }

    // -----------------------------------------------------------------------
    // Comments
    // -----------------------------------------------------------------------

    #[test]
    fn test_line_comment() {
        let kinds = tokenize("42 # this is a comment\n43");
        // No leading space on the next line so no Indent/Dedent
        assert_eq!(kinds, vec![
            TokenKind::Integer("42".into()),
            TokenKind::Newline,
            TokenKind::Integer("43".into()),
            TokenKind::Eof,
        ]);
    }

    // -----------------------------------------------------------------------
    // Indentation
    // -----------------------------------------------------------------------

    #[test]
    fn test_indent_dedent() {
        let kinds = tokenize("fn main():\n    42\n");
        assert!(kinds.contains(&TokenKind::Indent), "should contain Indent: {:?}", kinds);
        assert!(kinds.contains(&TokenKind::Dedent), "should contain Dedent: {:?}", kinds);
    }

    #[test]
    fn test_newline() {
        let kinds = tokenize("a\nb");
        assert!(kinds.contains(&TokenKind::Newline));
    }

    // -----------------------------------------------------------------------
    // Mixed
    // -----------------------------------------------------------------------

    #[test]
    fn test_function_declaration_tokens() {
        let source = "fn add(x: i32, y: i32) i32:\n    x + y\n";
        let kinds = tokenize(source);
        let expected = vec![
            TokenKind::Fn,
            TokenKind::Identifier("add".into()),
            TokenKind::LParen,
            TokenKind::Identifier("x".into()),
            TokenKind::Colon,
            TokenKind::Identifier("i32".into()),
            TokenKind::Comma,
            TokenKind::Identifier("y".into()),
            TokenKind::Colon,
            TokenKind::Identifier("i32".into()),
            TokenKind::RParen,
            TokenKind::Identifier("i32".into()),
            TokenKind::Colon,
            TokenKind::Newline,
            TokenKind::Indent,
            TokenKind::Identifier("x".into()),
            TokenKind::Plus,
            TokenKind::Identifier("y".into()),
            TokenKind::Newline,
            TokenKind::Dedent,
            TokenKind::Eof,
        ];
        assert_eq!(kinds, expected);
    }

    // -----------------------------------------------------------------------
    // Error handling
    // -----------------------------------------------------------------------

    #[test]
    fn test_at_token() {
        let kinds = tokenize("@");
        assert_eq!(kinds.len(), 2);
        assert_eq!(kinds[0], TokenKind::At);
        assert_eq!(kinds[1], TokenKind::Eof);
    }

    #[test]
    fn test_unexpected_character() {
        let kinds = tokenize("`");
        assert_eq!(kinds.len(), 2);
        assert!(matches!(&kinds[0], TokenKind::LexError(_)));
        assert_eq!(kinds[1], TokenKind::Eof);
    }
}
