use crate::ir::*;
use super::{GeneratedFile, BackendOutput, UiBackend};
use std::sync::atomic::{AtomicUsize, Ordering};

static EL_COUNTER: AtomicUsize = AtomicUsize::new(0);

fn fresh_el() -> String {
    let id = EL_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("_el{}", id)
}

pub struct WebBackend;

impl WebBackend {
    pub fn new() -> Self { Self }
}

impl UiBackend for WebBackend {
    fn name(&self) -> &str {
        "web"
    }

    fn target_triple(&self) -> &str {
        "wasm32-unknown-unknown"
    }

    fn generate(&self, program: &UiProgram) -> BackendOutput {
        let mut js = String::new();

        // Import ESM runtimes with absolute paths from server root
        js.push_str("// Generated by Kyle UI Compiler\n");
        js.push_str("// Target: Web (JS/DOM) — ES Modules\n\n");

        js.push_str("import { ReactiveState, Binding, createKyleEvent, enableLongPress, createVirtualList } from '/target/debug/reactivity.js';\n");
        js.push_str("import { createRouter, Router, routeParams, set_title, set_meta, navigate, navigate_back, navigate_replace } from '/target/debug/router.js';\n");
        js.push_str("import { A11yManager } from '/target/debug/a11y.js';\n");
        js.push_str("import { portalManager } from '/target/debug/portal.js';\n");
        js.push_str("import { ErrorBoundary } from '/target/debug/error_boundary.js';\n");
        js.push_str("import { getI18n, t, setLocale } from '/target/debug/i18n.js';\n");
        js.push_str("const _i18n = getI18n();\n");
        js.push_str("const _a11y = new A11yManager();\n\n");

        // Generate styles
        let style_js = generate_styles(&program.styles);
        js.push_str(&style_js);

        // Generate animations
        let anim_js = generate_animations(&program.animations);
        js.push_str(&anim_js);

        // Determine component name from view path — always export as 'render'
        let comp_name = "render".to_string();

        // Generate component function (exported at end)
        js.push_str("function render(container, initialState = {}) {\n");
        js.push_str("  const state = new ReactiveState(initialState);\n");
        js.push_str("  // Lifecycle hooks\n");

        // Translate code blocks (@(...)) to JS
        for block in &program.code_blocks {
            let js_block = translate_kyle_block_to_js(block);
            if !js_block.is_empty() {
                js.push_str("  // From Kyle block:\n");
                for line in js_block.lines() {
                    js.push_str(&format!("  {}\n", line));
                }
            }
        }

        // Call on_created if defined
        js.push_str("  if (typeof on_created === 'function') on_created();\n");

        // Set up on_updated — called on ANY state change
        js.push_str("  if (typeof on_updated === 'function') {\n");
        js.push_str("    state.onAnyChange((key) => {\n");
        js.push_str("      on_updated(new Set([key]));\n");
        js.push_str("    });\n");
        js.push_str("  }\n");

        js.push_str("  const el = document.createDocumentFragment();\n");

        for node in &program.body {
            gen_node(node, &mut js, 2, "el", "");
        }

        js.push_str("  // Set up lifecycle: on_mounted / on_unmounted\n");
        js.push_str("  const _lifecycle = {\n");
        js.push_str("    mounted: typeof on_mounted === 'function' ? () => on_mounted() : null,\n");
        js.push_str("    unmounted: typeof on_unmounted === 'function' ? () => on_unmounted() : null,\n");
        js.push_str("    updated: typeof on_updated === 'function' ? (changed) => on_updated(changed) : null,\n");
        js.push_str("  };\n");
        js.push_str("  return { element: el, state, lifecycle: _lifecycle };\n");
        js.push_str("}\n\n");

        // Generate component renderers from resolved dependencies
        for comp in &program.component_renderers {
            let comp_name = &comp.name;
            js.push_str(&format!("\n// Component renderer: {}\n", comp_name));
            js.push_str(&format!("function render_{}(params = {{}}) {{\n", comp_name));
            js.push_str("  const state = new ReactiveState({});\n");
            js.push_str("  // Lifecycle hooks\n");

            // Code blocks for this component
            for block in &comp.code_blocks {
                let js_block = translate_kyle_block_to_js(block);
                if !js_block.is_empty() {
                    js.push_str("  // From Kyle block:\n");
                    for line in js_block.lines() {
                        js.push_str(&format!("  {}\n", line));
                    }
                }
            }

            // Call on_created if defined
            js.push_str("  if (typeof on_created === 'function') on_created();\n");

            // Set up on_updated — called on ANY state change
            js.push_str("  if (typeof on_updated === 'function') {\n");
            js.push_str("    state.onAnyChange((key) => {\n");
            js.push_str("      on_updated(new Set([key]));\n");
            js.push_str("    });\n");
            js.push_str("  }\n");

            js.push_str("  const el = document.createDocumentFragment();\n");
            for node in &comp.body {
                gen_node(node, &mut js, 2, "el", "");
            }
            js.push_str("  // Lifecycle hooks for mounting/unmounting\n");
            js.push_str("  const _lifecycle = {\n");
            js.push_str("    mounted: typeof on_mounted === 'function' ? () => on_mounted() : null,\n");
            js.push_str("    unmounted: typeof on_unmounted === 'function' ? () => on_unmounted() : null,\n");
            js.push_str("    updated: typeof on_updated === 'function' ? (changed) => on_updated(changed) : null,\n");
            js.push_str("  };\n");
            js.push_str("  return { element: el, state, lifecycle: _lifecycle };\n");
            js.push_str("}\n");
        }

        // Extract app title/icon from body for top-level initialization
        for node in &program.body {
            if let UiNode::Element { tag, attrs, .. } = node {
                if tag == &ComponentTag::App {
                    for a in attrs {
                        if a.name == "title" {
                            let val = match &a.value {
                                AttrValue::String(v) => format!("{:?}", v),
                                AttrValue::Expr(v) => v.clone(),
                                _ => continue,
                            };
                            if !val.is_empty() {
                                js.push_str(&format!("document.title = {};\n", val));
                            }
                        }
                        if a.name == "icon" {
                            let val = match &a.value {
                                AttrValue::String(v) => format!("{:?}", v),
                                AttrValue::Expr(v) => v.clone(),
                                _ => continue,
                            };
                            if !val.is_empty() {
                                js.push_str(&format!("let _ic = document.querySelector('link[rel*=\"icon\"]'); if (!_ic) {{ _ic = document.createElement('link'); _ic.rel = 'icon'; document.head.appendChild(_ic); }} _ic.href = {};\n", val));
                            }
                        }
                    }
                }
            }
        }

        // Route registration from RouteConfig
        if !program.routes.is_empty() {
            js.push_str("\n// Register and start router\n");
            js.push_str("if (typeof window !== 'undefined') {\n");
            js.push_str("  if (!window.__KYLE_ROUTES) window.__KYLE_ROUTES = {};\n");
            for route in &program.routes {
                // Use component-specific renderer if available
                let comp_name = &route.component;
                let func_name = format!("render_{}", comp_name);
                // Check if a component renderer exists with this name
                let has_renderer = program.component_renderers.iter()
                    .any(|c| c.name == *comp_name);
                if has_renderer {
                    js.push_str(&format!("  window.__KYLE_ROUTES[{:?}] = {};\n", route.path, func_name));
                } else {
                    js.push_str(&format!("  window.__KYLE_ROUTES[{:?}] = render;\n", route.path));
                }
            }
            // Create and start router
            js.push_str("  const router = createRouter({ container: document.getElementById('app') });\n");
            js.push_str("  router.start();\n");
            js.push_str("}\n\n");
        }

        // Export render function
        js.push_str("export { render };\n");

        // Build HTML shell (adapts if routes exist — router handles rendering)
        let has_routes = !program.routes.is_empty();
        let html = generate_html(!has_routes);

        BackendOutput {
            files: vec![GeneratedFile {
                path: format!("ui-runtime.js"),
                content: js,
            }],
            html_shell: Some(html),
        }
    }
}

fn gen_node(node: &UiNode, js: &mut String, indent: usize, parent: &str, model: &str) {
    let el = fresh_el();
    let ind = " ".repeat(indent);
    let ind2 = " ".repeat(indent + 2);

    match node {
        UiNode::Element { tag, attrs, children } => {
            // Detect form model context
            let mut child_model = model;
            if tag == &ComponentTag::Form {
                for a in attrs {
                    if a.name == "model" {
                        if let AttrValue::Expr(ref v) = a.value {
                            child_model = v.trim_start_matches('@');
                        }
                    }
                }
            }

            let tag_js = js_tag(tag);
            if tag == &ComponentTag::FilePicker {
                let mut accept = String::new();
                let mut multiple = false;
                let mut on_select = String::new();
                let mut field = String::new();
                for a in attrs {
                    match a.name.as_str() {
                        "accept" => if let AttrValue::String(ref v) = a.value { accept = v.clone(); },
                        "multiple" => multiple = true,
                        "on_select" => if let AttrValue::Expr(ref v) = a.value { on_select = v.clone(); },
                        "field" => if let AttrValue::String(ref v) = a.value { field = v.clone(); },
                        _ => {}
                    }
                }
                // If field= is set and there's a model, auto-generate the callback
                let single_callback = if !field.is_empty() && !child_model.is_empty() {
                    format!("(fileData) => {{ state['{}'] = {{ ...(state['{}'] || {{}}), '{}': fileData }}; }}", child_model, child_model, field)
                } else if !on_select.is_empty() {
                    format!("({})", on_select.clone())
                } else {
                    String::new()
                };
                let multi_callback = if !field.is_empty() && !child_model.is_empty() {
                    format!("(files) => {{ state['{}'] = {{ ...(state['{}'] || {{}}), '{}': files }}; }}", child_model, child_model, field)
                } else if !on_select.is_empty() {
                    format!("({})", on_select.clone())
                } else {
                    String::new()
                };
                // Generate file input + handler
                let input_el = fresh_el();
                js.push_str(&format!("{}// FilePicker\n", ind));
                js.push_str(&format!("{}const {} = document.createElement('input');\n", ind, input_el));
                js.push_str(&format!("{}{}.type = 'file';\n", ind, input_el));
                if !accept.is_empty() {
                    js.push_str(&format!("{}{}.accept = {:?};\n", ind, input_el, accept));
                }
                if multiple {
                    js.push_str(&format!("{}{}.multiple = true;\n", ind, input_el));
                }
                js.push_str(&format!("{}{}.style.display = 'none';\n", ind, input_el));
                // Click handler triggers file picker
                js.push_str(&format!("{}{}.addEventListener('change', async () => {{\n", ind, input_el));
                if multiple {
                    js.push_str(&format!("{}  const files = [];\n", ind));
                    js.push_str(&format!("{}  for (const f of {}.files) {{\n", ind, input_el));
                    js.push_str(&format!("{}    const buf = await f.arrayBuffer();\n", ind));
                    js.push_str(&format!("{}    files.push({{ name: f.name, size: f.size, mime: f.type, content: new Uint8Array(buf), last_modified: f.lastModified }});\n", ind));
                    js.push_str(&format!("{}  }}\n", ind));
                    if !multi_callback.is_empty() {
                        js.push_str(&format!("{}  ({})(files);\n", ind, multi_callback));
                    }
                } else {
                    js.push_str(&format!("{}  const f = {}.files[0];\n", ind, input_el));
                    js.push_str(&format!("{}  if (!f) return;\n", ind));
                    js.push_str(&format!("{}  const buf = await f.arrayBuffer();\n", ind));
                    js.push_str(&format!("{}  const fileData = {{ name: f.name, size: f.size, mime: f.type, content: new Uint8Array(buf), last_modified: f.lastModified }};\n", ind));
                    if !single_callback.is_empty() {
                        js.push_str(&format!("{}  ({})(fileData);\n", ind, single_callback));
                    }
                }
                js.push_str(&format!("{}}});\n", ind));
                // Trigger click on mount
                js.push_str(&format!("{}{}.click();\n", ind, input_el));
                js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, input_el));
                return;
            }

            if tag == &ComponentTag::Portal {
                let mut target = "body";
                for a in attrs {
                    if a.name == "target" {
                        if let AttrValue::String(ref v) = a.value { target = v; }
                    }
                }
                js.push_str(&format!("{}// Portal: render to '{}'\n", ind, target));
                for child in children {
                    gen_node(child, js, indent, &format!("{}_content", el), model);
                }
                js.push_str(&format!("{}if (typeof {}_content !== 'undefined') {{\n", ind, el));
                js.push_str(&format!("{}  portalManager.create({}_content, {:?});\n", ind, el, target));
                js.push_str(&format!("{}}}\n", ind));
                return;
            }
            if tag == &ComponentTag::ErrorBoundary {
                let b = fresh_el();
                js.push_str(&format!("{}// Error boundary\n", ind));
                js.push_str(&format!("{}const {} = new ErrorBoundary();\n", ind, b));
                js.push_str(&format!("{}const {}_wrap = {}.wrap(() => {{\n", ind, b, b));
                js.push_str(&format!("{}  const {}_c = document.createDocumentFragment();\n", ind, b));
                for child in children {
                    gen_node(child, js, indent + 2, &format!("{}_c", b), model);
                }
                js.push_str(&format!("{}  return {}_c;\n", ind, b));
                js.push_str(&format!("{}}});\n", ind));
                js.push_str(&format!("{}const {}_r = {}_wrap();\n", ind, b, b));
                js.push_str(&format!("{}if ({}_r) {{ {}.appendChild({}_r); }}\n", ind, b, parent, b));
                return;
            }
            if tag == &ComponentTag::Slot {
                let mut name = "default";
                for a in attrs {
                    if a.name == "name" {
                        if let AttrValue::String(ref v) = a.value { name = v; }
                    }
                }
                js.push_str(&format!("{}// Outlet: '{}'\n", ind, name));
                js.push_str(&format!("{}portalManager.registerOutlet({:?}, {});\n", ind, name, el));
            }
            // Check for virtual list BEFORE element creation
            let mut item_height = 0i32;
            let is_virtual = {
                let mut v = false;
                if tag == &ComponentTag::List || tag == &ComponentTag::View {
                    for a in attrs {
                        if a.name == "virtual" { v = true; }
                        if a.name == "item_height" {
                            if let AttrValue::String(ref s) = a.value {
                                item_height = s.parse::<i32>().unwrap_or(0);
                            }
                        }
                    }
                }
                v && item_height > 0
            };

            if is_virtual {
                let mut for_item = String::new();
                let mut for_list = String::new();
                let mut for_body: Vec<&UiNode> = Vec::new();
                for child in children {
                    if let UiNode::For { item, list, body } = child {
                        for_item = item.clone();
                        for_list = list.clone();
                        for_body = body.iter().collect();
                    }
                }
                if !for_list.is_empty() {
                    js.push_str(&format!("{}createVirtualList({}, {}.length, {}, (el, idx) => {{\n", ind, parent, for_list, item_height));
                    js.push_str(&format!("{}  const {} = {}[idx];\n", ind, for_item, for_list));
                    for child in &for_body {
                        gen_node(child, js, indent + 2, "el", model);
                    }
                    js.push_str(&format!("{}}}, {{ height: '100%' }});\n", ind));
                } else {
                    js.push_str(&format!("{}const {} = document.createElement('{}');\n", ind, el, js_tag(tag)));
                    gen_attrs(attrs, js, indent, &el, js_tag(tag));
                    gen_events(attrs, js, indent, &el, child_model);
                    js.push_str(&format!("{}A11yManager.applyAria({}, {:?});\n", ind, el, tag.as_str()));
                    for child in children { gen_node(child, js, indent + 2, &el, child_model); }
                    js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, el));
                }
                return;
            }

            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const {} = document.createElement('{}');\n", ind, el, tag_js));
            gen_attrs(attrs, js, indent, &el, tag_js);
            gen_events(attrs, js, indent, &el, child_model);

            // App component: handle title and icon
            if tag == &ComponentTag::App {
                for a in attrs {
                    if a.name == "title" {
                        let val = match &a.value {
                            AttrValue::String(v) => format!("{:?}", v),
                            AttrValue::Expr(v) => v.clone(),
                            AttrValue::Flag => String::new(),
                        };
                        if !val.is_empty() {
                            js.push_str(&format!("{}document.title = {};\n", ind, val));
                        }
                    }
                    if a.name == "icon" {
                        let val = match &a.value {
                            AttrValue::String(v) => format!("{:?}", v),
                            AttrValue::Expr(v) => v.clone(),
                            AttrValue::Flag => String::new(),
                        };
                        if !val.is_empty() {
                            js.push_str(&format!("{}let _icon = document.querySelector('link[rel*=\"icon\"]'); if (!_icon) {{ _icon = document.createElement('link'); _icon.rel = 'icon'; document.head.appendChild(_icon); }} _icon.href = {};\n", ind, val));
                        }
                    }
                }
            }

            // Link component: intercept clicks for client-side navigation
            if tag == &ComponentTag::Link {
                for a in attrs {
                    if a.name == "to" {
                        let target = match &a.value {
                            AttrValue::String(v) => format!("{:?}", v),
                            AttrValue::Expr(v) => v.clone(),
                            AttrValue::Flag => String::new(),
                        };
                        js.push_str(&format!("{}{}.addEventListener('click', (e) => {{ e.preventDefault(); navigate({}); }});\n", ind, el, target));
                    }
                }
            }

            js.push_str(&format!("{}A11yManager.applyAria({}, {:?});\n", ind, el, tag.as_str()));
            for child in children {
                gen_node(child, js, indent + 2, &el, child_model);
            }
            js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, el));
        }
        UiNode::SelfClosing { tag, attrs } => {
            // FilePicker: generate hidden file input with FileReader
            if tag == &ComponentTag::FilePicker {
                let mut accept = String::new();
                let mut multiple = false;
                let mut on_select = String::new();
                let mut field = String::new();
                for a in attrs {
                    match a.name.as_str() {
                        "accept" => if let AttrValue::String(ref v) = a.value { accept = v.clone(); },
                        "multiple" => multiple = true,
                        "on_select" => if let AttrValue::Expr(ref v) = a.value { on_select = v.clone(); },
                        "field" => if let AttrValue::String(ref v) = a.value { field = v.clone(); },
                        _ => {}
                    }
                }
                let single_callback = if !field.is_empty() && !model.is_empty() {
                    format!("(fileData) => {{ state['{}'] = {{ ...(state['{}'] || {{}}), '{}': fileData }}; }}", model, model, field)
                } else if !on_select.is_empty() {
                    format!("({})", on_select.clone())
                } else {
                    String::new()
                };
                let mut multi_callback = if !field.is_empty() && !model.is_empty() {
                    format!("(files) => {{ state['{}'] = {{ ...(state['{}'] || {{}}), '{}': files }}; }}", model, model, field)
                } else if !on_select.is_empty() {
                    format!("({})", on_select.clone())
                } else {
                    String::new()
                };
                // For multi on_select, use the same callback name
                if multi_callback.is_empty() && !on_select.is_empty() {
                    multi_callback = on_select.clone();
                }
                let input_el = fresh_el();
                js.push_str(&format!("{}// FilePicker\n", ind));
                js.push_str(&format!("{}const {} = document.createElement('input');\n", ind, input_el));
                js.push_str(&format!("{}{}.type = 'file';\n", ind, input_el));
                if !accept.is_empty() {
                    js.push_str(&format!("{}{}.accept = {:?};\n", ind, input_el, accept));
                }
                if multiple {
                    js.push_str(&format!("{}{}.multiple = true;\n", ind, input_el));
                }
                js.push_str(&format!("{}{}.style.display = 'none';\n", ind, input_el));
                js.push_str(&format!("{}{}.addEventListener('change', async () => {{\n", ind, input_el));
                if multiple {
                    js.push_str(&format!("{}  const files = [];\n", ind));
                    js.push_str(&format!("{}  for (const f of {}.files) {{\n", ind, input_el));
                    js.push_str(&format!("{}    const buf = await f.arrayBuffer();\n", ind));
                    js.push_str(&format!("{}    files.push({{ name: f.name, size: f.size, mime: f.type, content: new Uint8Array(buf), last_modified: f.lastModified }});\n", ind));
                    js.push_str(&format!("{}  }}\n", ind));
                    if !multi_callback.is_empty() {
                        js.push_str(&format!("{}  ({})(files);\n", ind, multi_callback));
                    }
                } else {
                    js.push_str(&format!("{}  const f = {}.files[0];\n", ind, input_el));
                    js.push_str(&format!("{}  if (!f) return;\n", ind));
                    js.push_str(&format!("{}  const buf = await f.arrayBuffer();\n", ind));
                    js.push_str(&format!("{}  const fileData = {{ name: f.name, size: f.size, mime: f.type, content: new Uint8Array(buf), last_modified: f.lastModified }};\n", ind));
                    if !single_callback.is_empty() {
                        js.push_str(&format!("{}  ({})(fileData);\n", ind, single_callback));
                    }
                }
                js.push_str(&format!("{}}});\n", ind));
                js.push_str(&format!("{}{}.click();\n", ind, input_el));
                js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, input_el));
                return;
            }

            let tag_js = js_tag(tag);
            js.push_str(&format!("{}const {} = document.createElement('{}');\n", ind, el, tag_js));
            gen_attrs(attrs, js, indent, &el, tag_js);
            gen_events(attrs, js, indent, &el, model);

            // Link component: intercept clicks for client-side navigation
            if tag == &ComponentTag::Link {
                for a in attrs {
                    if a.name == "to" {
                        let target = match &a.value {
                            AttrValue::String(v) => format!("{:?}", v),
                            AttrValue::Expr(v) => v.clone(),
                            AttrValue::Flag => String::new(),
                        };
                        js.push_str(&format!("{}{}.addEventListener('click', (e) => {{ e.preventDefault(); navigate({}); }});\n", ind, el, target));
                    }
                }
            }

            js.push_str(&format!("{}A11yManager.applyAria({}, {:?});\n", ind, el, tag.as_str()));
            js.push_str(&format!("{}{}.appendChild({});\n", ind, parent, el));
        }
        UiNode::Slot { name, fallback } => {
            js.push_str(&format!("{}// Slot: {}\n", ind, name));
            if !fallback.is_empty() {
                for child in fallback {
                    gen_node(child, js, indent, parent, model);
                }
            }
        }
        UiNode::If { condition, then_branch, else_branch } => {
            let js_cond = kyle_to_js_expr(condition);
            js.push_str(&format!("{}if ({}) {{\n", ind, js_cond));
            for child in then_branch {
                gen_node(child, js, indent + 4, parent, model);
            }
            if !else_branch.is_empty() {
                js.push_str(&format!("{}}} else {{\n", ind));
                for child in else_branch {
                    gen_node(child, js, indent + 4, parent, model);
                }
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        UiNode::For { item, list, body } => {
            // Convert Kyle range syntax "0..30" to JS array
            let js_list = if list.contains("..") {
                let parts: Vec<&str> = list.split("..").collect();
                if parts.len() == 2 {
                    let start = parts[0].trim();
                    let end = parts[1].trim();
                    let start_n: i32 = start.parse().unwrap_or(0);
                    let end_n: i32 = end.parse().unwrap_or(0);
                    let len = (end_n - start_n).max(0);
                    format!("Array.from({{length: {}}}, (_, i) => i + {})", len, start_n)
                } else {
                    list.to_string()
                }
            } else {
                list.to_string()
            };
            js.push_str(&format!("{}for (const {} of {}) {{\n", ind, item, kyle_to_js_expr(&js_list)));
            for child in body {
                gen_node(child, js, indent + 4, parent, model);
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        UiNode::Match { expr, cases } => {
            js.push_str(&format!("{}switch ({}) {{\n", ind, expr));
            for case in cases {
                js.push_str(&format!("{}  case {}:\n", ind, case.pattern));
                for child in &case.body {
                    gen_node(child, js, indent + 8, parent, model);
                }
                js.push_str(&format!("{}    break;\n", ind));
            }
            js.push_str(&format!("{}}}\n", ind));
        }
        UiNode::Expr(e) => {
            let js_expr = translate_kyle_block_to_js(e);
            if js_expr.trim().is_empty() || js_expr == *e {
                js.push_str(&format!("{}// Expression: {}\n", ind, e));
                js.push_str(&format!("{}{}\n", ind, e));
            } else {
                for line in js_expr.lines() {
                    let trimmed = line.trim();
                    if !trimmed.is_empty() && !trimmed.starts_with('#') {
                        js.push_str(&format!("{}{}\n", ind, trimmed));
                    }
                }
            }
        }
        UiNode::CodeBlock(code) => {
            let js_block = translate_kyle_block_to_js(code);
            if !js_block.is_empty() {
                js.push_str(&format!("{}// From inline Kyle block:\n", ind));
                for line in js_block.lines() {
                    js.push_str(&format!("{}{}\n", ind, line));
                }
            }
        }
        UiNode::Text(text) => {
            js.push_str(&format!("{}{}.appendChild(document.createTextNode({:?}));\n", ind, parent, text));
        }
    }
}

/// Replace @name references in an expression with state.get('name').
/// e.g. "@count + 1" → "state.get('count') + 1"
fn strip_at_refs(val: &str) -> String {
    let mut result = String::new();
    let mut last = 0;
    let chars: Vec<char> = val.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '@' {
            result.push_str(&val[last..i]);
            let start = i + 1;
            let key_len = chars[start..].iter().take_while(|c| c.is_alphanumeric() || **c == '_').count();
            if key_len > 0 && start + key_len <= chars.len() {
                let key: String = chars[start..start + key_len].iter().collect();
                result.push_str(&format!("state.get('{}')", key));
                i = start + key_len;
                last = i;
                continue;
            }
        }
        i += 1;
    }
    if last < chars.len() {
        result.push_str(&val[last..]);
    }
    result
}

/// Replace @name references in a string with state.get("name") for reactive binding.
/// e.g. "Clicks: @count" → "Clicks: " + state.get("count")
fn interpolate_state(val: &str) -> String {
    let mut result = String::new();
    let mut last = 0;
    for (i, _) in val.match_indices('@') {
        if i > last {
            result.push_str(&format!("{:?} + ", &val[last..i]));
        }
        let rest = &val[i + 1..];
        let key_len = rest.chars().take_while(|c| c.is_alphanumeric() || *c == '_').count();
        if key_len > 0 {
            let key = &rest[..key_len];
            result.push_str(&format!("state.get({:?}) + ", key));
            last = i + 1 + key_len;
        } else {
            result.push('@');
            last = i + 1;
        }
    }
    if last < val.len() {
        result.push_str(&format!("{:?}", &val[last..]));
    } else {
        // Remove trailing " + "
        if result.ends_with(" + ") {
            result.truncate(result.len() - 3);
        }
    }
    result
}

fn gen_attrs(attrs: &[UiAttr], js: &mut String, indent: usize, el: &str, tag: &str) {
    let ind = " ".repeat(indent + 2);
    for attr in attrs {
        // Check if this is a style-related attribute
        if let Some(css_prop) = style_attr_to_css(&attr.name) {
            match &attr.value {
                AttrValue::String(val) => {
                    let css_val = attr_style_value(&attr.name, val);
                    js.push_str(&format!("{}{}.style[{}] = {};\n", ind, el, css_prop, css_val));
                }
                AttrValue::Expr(expr) => {
                    let css_val = if is_simple_key(expr) {
                        format!("state.get({:?})", expr)
                    } else {
                        format!("{}", expr)
                    };
                    js.push_str(&format!("{}const __upd_{}_{} = () => {{ {}.style[{}] = {}; }};\n", ind, el, attr.name, el, css_prop, css_val));
                    js.push_str(&format!("{}__upd_{}_{}();\n", ind, el, attr.name));
                    // Watch count as a heuristic
                    js.push_str(&format!("{}state.watch('count', __upd_{}_{});\n", ind, el, attr.name));
                }
                AttrValue::Flag => {
                    js.push_str(&format!("{}{}.style[{}] = '1';\n", ind, el, css_prop));
                }
            }
            continue;
        }
        // Check for layout attribute (flexbox)
        if attr.name == "layout" {
            if let AttrValue::String(val) = &attr.value {
                let (ai, jc) = layout_to_flex(val);
                js.push_str(&format!("{}{}.style.display = 'flex';\n", ind, el));
                if !ai.is_empty() {
                    js.push_str(&format!("{}{}.style.alignItems = '{}';\n", ind, el, ai));
                }
                if !jc.is_empty() {
                    js.push_str(&format!("{}{}.style.justifyContent = '{}';\n", ind, el, jc));
                }
            }
            continue;
        }
        // Check for spacing attribute (gap in flexbox)
        if attr.name == "spacing" {
            if let AttrValue::String(val) = &attr.value {
                let v = if val.chars().all(|c| c.is_ascii_digit()) {
                    format!("{}px", val)
                } else { val.clone() };
                js.push_str(&format!("{}{}.style.gap = '{}';\n", ind, el, v));
            }
            continue;
        }
        // Regular attribute handling
        match &attr.value {
            AttrValue::String(val) => {
                match attr.name.as_str() {
                    "tpl" | "style" => {
                        js.push_str(&format!("{}applyStyle({}, {:?});\n", ind, el, val));
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation({}, {:?});\n", ind, el, val));
                    }
                    "text" | "value" | "label" => {
                        if val.contains('@') {
                            let js_expr = interpolate_state(val);
                            js.push_str(&format!("{}const __upd = () => {{ {}.textContent = {}; }};\n", ind, el, js_expr));
                            js.push_str(&format!("{}__upd();\n", ind));
                            for (_, key) in val.match_indices('@') {
                                let rest = &val[val[..].find('@').unwrap() + 1..]; // simplified
                            }
                            // watch all @keys in the string
                            let mut pos = 0;
                            while let Some(at) = val[pos..].find('@') {
                                let start = pos + at + 1;
                                let end = val[start..].chars().take_while(|c| c.is_alphanumeric() || *c == '_').count();
                                if end > 0 {
                                    let key = &val[start..start + end];
                                    js.push_str(&format!("{}state.watch({:?}, __upd);\n", ind, key));
                                }
                                pos = start + end;
                            }
                        } else {
                            js.push_str(&format!("{}{}.textContent = {:?};\n", ind, el, val));
                        }
                    }
                    "class" | "id" | "type" | "placeholder" | "src" | "alt" | "href" => {
                        js.push_str(&format!("{}{}.setAttribute({:?}, {:?});\n", ind, el, attr.name, val));
                    }
                    "fallback" => {
                        js.push_str(&format!("{}{}.setAttribute('onerror', 'this.src=\"{}\"');\n", ind, el, val));
                    }
                    _ => {
                        // Unknown attr: try as style first, else setAttribute
                        let css_name = attr.name.replace("_", "-");
                        js.push_str(&format!("{}{}.style['{}'] = '{}';\n", ind, el, css_name, val));
                    }
                }
            }
            AttrValue::Expr(expr) => {
                match attr.name.as_str() {
                    "bind" => {
                        js.push_str(&format!("{}Binding.twoWay({}, state, {:?}, 'input');\n", ind, el, expr));
                    }
                    "text" | "value" => {
                        // For computed expressions, use watch-based approach
                        if is_simple_key(expr) {
                            js.push_str(&format!("{}Binding.oneWay({}, 'textContent', state, {:?});\n", ind, el, expr));
                        } else {
                            let js_expr = kyle_to_js_expr(expr);
                            let upd_name = format!("__upd_{}_{}", el, attr.name);
                            js.push_str(&format!("{}const {} = () => {{ {}.textContent = {}; }};\n", ind, upd_name, el, js_expr));
                            js.push_str(&format!("{}__upd_{}_{}();\n", ind, el, attr.name));
                            let state_keys = extract_state_keys(expr);
                            for key in &state_keys {
                                js.push_str(&format!("{}state.watch({:?}, __upd_{}_{});\n", ind, key, el, attr.name));
                            }
                        }
                    }
                    "src" => {
                        if is_simple_key(expr) {
                            js.push_str(&format!("{}if (state.get({:?}) != null) {}.src = state.get({:?});\n", ind, expr, el, expr));
                        } else {
                            let js_expr = kyle_to_js_expr(expr);
                            let upd_name = format!("__upd_{}_{}", el, attr.name);
                            js.push_str(&format!("{}const {} = () => {{ if ({}) {}.src = {}; }};\n", ind, upd_name, js_expr, el, js_expr));
                            js.push_str(&format!("{}__upd_{}_{}();\n", ind, el, attr.name));
                            let state_keys = extract_state_keys(expr);
                            for key in &state_keys {
                                js.push_str(&format!("{}state.watch({:?}, __upd_{}_{});\n", ind, key, el, attr.name));
                            }
                        }
                    }
                    "alt" => {
                        js.push_str(&format!("{}{}.alt = state.get({:?});\n", ind, el, expr));
                    }
                    "tpl" | "style" => {
                        if is_simple_key(expr) {
                            js.push_str(&format!("{}applyStyle({}, {:?});\n", ind, el, expr));
                        } else {
                            js.push_str(&format!("{}applyStyle({}, state.get({:?}));\n", ind, el, expr));
                        }
                    }
                    "animation" => {
                        js.push_str(&format!("{}applyAnimation({}, state.get({:?}));\n", ind, el, expr));
                    }
                    "checked" => {
                        js.push_str(&format!("{}Binding.oneWay({}, 'checked', state, {:?});\n", ind, el, expr));
                    }
                    "disabled" => {
                        js.push_str(&format!("{}Binding.oneWay({}, 'disabled', state, {:?});\n", ind, el, expr));
                    }
                    "click" | "change" | "input" | "mouse_enter" | "mouse_leave"
                    | "focus" | "blur" | "keydown" | "keyup" | "submit" | "scroll"
                    | "dblclick" | "context_menu" | "mouse_down" | "mouse_up"
                    | "mouse_move" | "touch_start" | "touch_end" | "touch_move"
                    | "long_press" => {}
                    _ => {
                        let css_name = attr.name.replace("_", "-");
                        if is_simple_key(expr) {
                            js.push_str(&format!("{}{}.style['{}'] = state.get({:?});\n", ind, el, css_name, expr));
                        } else {
                            let upd_name = format!("__upd_{}_{}", el, attr.name);
                            js.push_str(&format!("{}const {} = () => {{ {}.style['{}'] = {}; }};\n", ind, upd_name, el, css_name, expr));
                            js.push_str(&format!("{}__upd_{}_{}();\n", ind, el, attr.name));
                        }
                    }
                }
            }
            AttrValue::Flag => {
                if attr.name == "lazy" && tag == "img" {
                    // Native browser lazy loading + fade in
                    js.push_str(&format!("{}{}.loading = 'lazy';\n", ind, el));
                    js.push_str(&format!("{}{}.style.opacity = '0.5';\n", ind, el));
                    js.push_str(&format!("{}{}.style.transition = 'opacity 0.3s';\n", ind, el));
                    js.push_str(&format!("{}{}.onload = () => {{ {}.style.opacity = '1'; }};\n", ind, el, el));
                } else {
                    js.push_str(&format!("{}{}.setAttribute({:?}, '');\n", ind, el, attr.name));
                }
            }
        }
    }
}

/// Map style attribute names to CSS property strings (quoted)
fn style_attr_to_css(name: &str) -> Option<String> {
    let prop = match name {
        "font_size" => "fontSize",
        "font_weight" => "fontWeight",
        "font_family" => "fontFamily",
        "color" => "color",
        "background" | "bg" => "background",
        "background_color" => "backgroundColor",
        "padding" => "padding",
        "margin" => "margin",
        "width" | "w" => "width",
        "height" | "h" => "height",
        "min_width" => "minWidth",
        "max_width" => "maxWidth",
        "min_height" => "minHeight",
        "max_height" => "maxHeight",
        "border_radius" => "borderRadius",
        "border" => "border",
        "opacity" => "opacity",
        "overflow" => "overflow",
        "display" => "display",
        "gap" => "gap",
        "z_index" => "zIndex",
        "cursor" => "cursor",
        "text_align" => "textAlign",
        "line_height" => "lineHeight",
        "letter_spacing" => "letterSpacing",
        "transform" => "transform",
        "transition" => "transition",
        "box_shadow" | "shadow" => "boxShadow",
        "flex" => "flex",
        "flex_grow" => "flexGrow",
        "flex_shrink" => "flexShrink",
        "flex_basis" => "flexBasis",
        "flex_direction" => "flexDirection",
        "align_items" => "alignItems",
        "align_self" => "alignSelf",
        "justify_content" => "justifyContent",
        "position" => "position",
        "top" => "top",
        "right" => "right",
        "bottom" => "bottom",
        "left" => "left",
        _ => return None,
    };
    Some(format!("'{}'", prop))
}

/// Convert a style attribute value to a JS expression
fn attr_style_value(name: &str, val: &str) -> String {
    let v = val.trim().trim_matches('"');
    // Handle color("#hex") → '#hex'
    if v.starts_with("color(") {
        let inner = v.trim_start_matches("color(").trim_end_matches(')');
        return format!("'{}'", inner.trim_matches('"'));
    }
    // Handle spacing.all(N) → Npx  
    if v.starts_with("spacing.") || v.starts_with("Spacing.") {
        let inner = v.split('(').nth(1).and_then(|s| s.trim_end_matches(')').split(',').next());
        if let Some(n) = inner {
            let n = n.trim().trim_matches('"');
            if n.chars().all(|c| c.is_ascii_digit() || c == '.') {
                return format!("'{}px'", n);
            }
            return format!("'{}'", n);
        }
    }
    // Numbers -> add px for size-related properties
    let needs_px = matches!(name, "font_size" | "border_radius" | "gap" | "padding"
        | "margin" | "width" | "height" | "min_width" | "max_width"
        | "min_height" | "max_height" | "line_height" | "letter_spacing"
        | "top" | "right" | "bottom" | "left");
    if needs_px && v.chars().all(|c| c.is_ascii_digit() || c == '.') {
        return format!("'{}px'", v);
    }
    format!("'{}'", v)
}

/// Check if an expression is a simple state key (single identifier)
fn is_simple_key(expr: &str) -> bool {
    let trimmed = expr.trim();
    !trimmed.contains(' ') && !trimmed.contains('"') && !trimmed.contains('+')
        && !trimmed.contains('(') && !trimmed.contains(')')
}

/// Convert layout value to (alignItems, justifyContent)
fn layout_to_flex(layout: &str) -> (&str, &str) {
    match layout.trim().to_lowercase().as_str() {
        "center" => ("center", "center"),
        "start" => ("flex-start", "flex-start"),
        "end" => ("flex-end", "flex-end"),
        "stretch" => ("stretch", "stretch"),
        "top" | "start_top" => ("flex-start", "flex-start"),
        "bottom" | "end_bottom" => ("flex-end", "flex-end"),
        "center_x" | "hcenter" => ("center", "flex-start"),
        "center_y" | "vcenter" => ("flex-start", "center"),
        "space_between" => ("center", "space-between"),
        "space_around" => ("center", "space-around"),
        _ => ("", ""),
    }
}

fn gen_events(attrs: &[UiAttr], js: &mut String, indent: usize, el: &str, model: &str) {
    let ind = " ".repeat(indent + 2);
    // Handle field= for model binding
    if !model.is_empty() {
        for attr in attrs {
            if attr.name == "field" {
                if let AttrValue::String(ref field_name) = attr.value {
                    // Two-way binding: model.field <-> input value
                    js.push_str(&format!("{}// Field binding: {}.{}\n", ind, model, field_name));
                    // One-way: model -> input
                    js.push_str(&format!("{}{}.value = state['{}']?.{} ?? '';\n", ind, el, model, field_name));
                    js.push_str(&format!("{}{}.addEventListener('input', () => {{\n", ind, el));
                    js.push_str(&format!("{}  state['{}'] = {{ ...(state['{}'] || {{}}), '{}': {}.value }};\n", ind, model, model, field_name, el));
                    js.push_str(&format!("{}}});\n", ind));
                }
            }
            if attr.name == "bind" {
                // Skip bind when field is set
            }
        }
    }
    // Standard event listeners
    for attr in attrs {
        let event_name = match attr.name.as_str() {
            "click" => "click",
            "change" => "change",
            "input" => "input",
            "mouse_enter" => "mouseenter",
            "mouse_leave" => "mouseleave",
            "focus" => "focus",
            "blur" => "blur",
            "keydown" => "keydown",
            "keyup" => "keyup",
            "submit" => "submit",
            "scroll" => "scroll",
            "dblclick" => "dblclick",
            "context_menu" => "contextmenu",
            "mouse_down" => "mousedown",
            "mouse_up" => "mouseup",
            "mouse_move" => "mousemove",
            "touch_start" => "touchstart",
            "touch_end" => "touchend",
            "touch_move" => "touchmove",
            "long_press" => "longpress",
            _ => continue,
        };
        if let AttrValue::Expr(handler) = &attr.value {
            if event_name == "longpress" {
                js.push_str(&format!("{}enableLongPress({}, (e) => {{ {}(e); }});\n", ind, el, handler));
            } else {
                js.push_str(&format!("{}{}.addEventListener({:?}, (e) => {{ {}(createKyleEvent(e)); }});\n", ind, el, event_name, handler));
            }
        }
    }
}

fn js_tag(tag: &ComponentTag) -> &str {
    match tag {
        ComponentTag::View | ComponentTag::VStack | ComponentTag::HStack
        | ComponentTag::ZStack
        | ComponentTag::Card | ComponentTag::Surface
        | ComponentTag::Group | ComponentTag::Scroll => "div",
        ComponentTag::Text => "span",
        ComponentTag::Button => "button",
        ComponentTag::TextField => "input",
        ComponentTag::PasswordField => "input",
        ComponentTag::TextArea => "textarea",
        ComponentTag::Checkbox => "input",
        ComponentTag::Radio => "input",
        ComponentTag::Image | ComponentTag::Icon => "img",
        ComponentTag::Link => "a",
        ComponentTag::List => "ul",
        ComponentTag::Form => "form",
        ComponentTag::Modal | ComponentTag::Alert => "div",
        ComponentTag::Navbar | ComponentTag::Sidebar | ComponentTag::Footer => "div",
        ComponentTag::Canvas => "canvas",
        ComponentTag::Video => "video",
        ComponentTag::Audio => "audio",
        ComponentTag::Select => "select",
        ComponentTag::Slider => "input",
        ComponentTag::Switch => "input",
        ComponentTag::Progress => "progress",
        ComponentTag::Spinner => "div",
        ComponentTag::FilePicker => "input",
        _ => "div",
    }
}

/// Generate HTML shell from component config
fn generate_html(call_render: bool) -> String {
    let script = if call_render {
        r#"        import { render } from './target/debug/ui-runtime.js';
        const app = document.getElementById('app');
        const result = render();
        app.appendChild(result.element);"#.to_string()
    } else {
        r#"        import './target/debug/ui-runtime.js';"#.to_string()
    };
    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Kyle App</title>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: 100%; min-height: 100vh; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }}
      button, input, select, textarea {{ font: inherit; border: none; background: none; outline: none; }}
      button {{ cursor: pointer; }}
      a {{ color: inherit; text-decoration: none; }}
      ul, ol {{ list-style: none; }}
      img {{ max-width: 100%; display: block; }}
    </style>
</head>
<body>
    <div id="app"></div>
    <script type="module">
{}
    </script>
</body>
</html>
"#, script)
}

// ── Style Generator ──────────────────────────────────────────────

fn generate_styles(styles: &[StyleDecl]) -> String {
    let mut js = String::new();

    let mut has_media = false;
    js.push_str("const _style_data = {\n");
    for decl in styles {
        match decl {
            StyleDecl::Style { name, props, media, .. }
            | StyleDecl::Layout { name, props, media, .. }
            | StyleDecl::Template { name, props, media, .. } => {
                js.push_str(&format!("  '{}': {{\n", name));
                for prop in props {
                    let css_prop = to_css_name(&prop.name);
                    let css_val = to_css_value(&prop.name, &prop.value);
                    js.push_str(&format!("    '{}': '{}',\n", css_prop, css_val));
                }
                for mq in media {
                    has_media = true;
                    let mq_cond = to_media_condition(&mq.condition);
                    js.push_str(&format!("    '{}': {{\n", mq_cond));
                    for prop in &mq.props {
                        let css_prop = to_css_name(&prop.name);
                        let css_val = to_css_value(&prop.name, &prop.value);
                        js.push_str(&format!("      '{}': '{}',\n", css_prop, css_val));
                    }
                    js.push_str("    },\n");
                }
                js.push_str("  },\n");
            }
            StyleDecl::Theme { name, props } => {
                js.push_str(&format!("  'theme:{}': {{\n", name));
                for prop in props {
                    js.push_str(&format!("    '{}': '{}',\n", prop.name, prop.value));
                }
                js.push_str("  },\n");
            }
        }
    }
    js.push_str("};\n\n");

    // Export styles
    js.push_str("export const styles = _style_data;\n\n");

    js.push_str("export function applyStyle(el, styleName) {\n");
    js.push_str("  const s = _style_data[styleName];\n");
    js.push_str("  if (!s) return;\n");
    js.push_str("  const base = {};\n");
    js.push_str("  const mediaQueries = {};\n");
    js.push_str("  for (const [key, val] of Object.entries(s)) {\n");
    js.push_str("    if (key.startsWith('@media')) {\n");
    js.push_str("      mediaQueries[key] = val;\n");
    js.push_str("    } else {\n");
    js.push_str("      base[key] = val;\n");
    js.push_str("    }\n");
    js.push_str("  }\n");
    js.push_str("  for (const [prop, val] of Object.entries(base)) {\n");
    js.push_str("    el.style[prop] = val;\n");
    js.push_str("  }\n");
    js.push_str("  for (const [mq, rules] of Object.entries(mediaQueries)) {\n");
    js.push_str("    const mql = window.matchMedia(mq.replace('@media ', ''));\n");
    js.push_str("    const apply = () => {\n");
    js.push_str("      if (mql.matches) {\n");
    js.push_str("        for (const [prop, val] of Object.entries(rules)) {\n");
    js.push_str("          el.style[prop] = val;\n");
    js.push_str("        }\n");
    js.push_str("      }\n");
    js.push_str("    };\n");
    js.push_str("    apply();\n");
    js.push_str("    mql.addEventListener('change', apply);\n");
    js.push_str("  }\n");
    js.push_str("}\n\n");

    js
}

fn to_css_name(prop: &str) -> &str {
    match prop {
        "background" => "background",
        "color" => "color",
        "font_size" => "fontSize",
        "font_weight" => "fontWeight",
        "font_family" => "fontFamily",
        "line_height" => "lineHeight",
        "letter_spacing" => "letterSpacing",
        "text_align" => "textAlign",
        "border_radius" => "borderRadius",
        "border" => "border",
        "border_top" => "borderTop",
        "border_right" => "borderRight",
        "border_bottom" => "borderBottom",
        "border_left" => "borderLeft",
        "padding" => "padding",
        "margin" => "margin",
        "width" => "width",
        "height" => "height",
        "min_width" => "minWidth",
        "max_width" => "maxWidth",
        "min_height" => "minHeight",
        "max_height" => "maxHeight",
        "opacity" => "opacity",
        "cursor" => "cursor",
        "overflow" => "overflow",
        "display" => "display",
        "gap" => "gap",
        "z_index" => "zIndex",
        "shadow" => "boxShadow",
        "transform" => "transform",
        "transition" => "transition",
        "flex_direction" => "flexDirection",
        "flex_grow" => "flexGrow",
        "flex_shrink" => "flexShrink",
        "flex_basis" => "flexBasis",
        "align_items" => "alignItems",
        "justify_content" => "justifyContent",
        _ => prop, // passthrough
    }
}

fn to_css_value(prop: &str, val: &str) -> String {
    let val = val.trim();
    // Handle color(...) function (lowercase)
    if val.to_lowercase().starts_with("color(") {
        let inner = val.trim_start_matches("color(").trim_start_matches("Color(").trim_end_matches(')');
        let inner = inner.trim().trim_matches('"');
        if inner.starts_with('#') {
            return inner.to_string();
        }
        return "#333333".to_string();
    }
    // Handle spacing.(...) function
    if val.to_lowercase().starts_with("spacing") {
        if let Some(num) = val.split(|c: char| !c.is_ascii_digit()).find(|s| !s.is_empty()) {
            return format!("{}px", num);
        }
        return "0".to_string();
    }
    // Handle enum types: font_weight.bold → "bold", etc.
    let normalized = val.trim().to_lowercase();
    if normalized.starts_with("font_weight.") || normalized.starts_with("fontweight.") {
        let v = normalized.rsplit('.').next().unwrap_or("");
        return match v {
            "thin" => "100",
            "light" => "300",
            "normal" => "400",
            "medium" => "500",
            "semibold" | "semi_bold" => "600",
            "bold" => "700",
            "black" => "900",
            _ => "400",
        }.to_string();
    }
    if normalized.starts_with("text_align.") || normalized.starts_with("textalign.") {
        let v = normalized.rsplit('.').next().unwrap_or("");
        return match v {
            "left" => "left",
            "center" => "center",
            "right" => "right",
            "justify" => "justify",
            _ => "left",
        }.to_string();
    }
    if normalized.starts_with("display.") {
        let v = normalized.rsplit('.').next().unwrap_or("");
        return match v {
            "flex" => "flex",
            "grid" => "grid",
            "none" => "none",
            "block" => "block",
            "inline" => "inline",
            _ => "flex",
        }.to_string();
    }
    if normalized.starts_with("flex_direction.") || normalized.starts_with("flexdirection.") {
        let v = normalized.rsplit('.').next().unwrap_or("");
        return match v {
            "row" => "row",
            "column" | "col" => "column",
            "row_reverse" | "rowreverse" => "row-reverse",
            "column_reverse" | "columnreverse" => "column-reverse",
            _ => "column",
        }.to_string();
    }
    if normalized.starts_with("alignment.") || normalized.starts_with("align.") {
        let v = normalized.rsplit('.').next().unwrap_or("");
        return match v {
            "center" => "center",
            "start" | "flex_start" | "flexstart" => "flex-start",
            "end" | "flex_end" | "flexend" => "flex-end",
            "stretch" => "stretch",
            "space_between" | "spacebetween" => "space-between",
            "space_around" | "spacearound" => "space-around",
            "space_evenly" | "spaceevenly" => "space-evenly",
            "baseline" => "baseline",
            _ => "center",
        }.to_string();
    }
    if normalized.starts_with("cursor.") {
        let v = normalized.rsplit('.').next().unwrap_or("");
        return match v {
            "pointer" => "pointer",
            "default" => "default",
            "text" => "text",
            "wait" => "wait",
            "crosshair" => "crosshair",
            "not_allowed" | "notallowed" => "not-allowed",
            "grab" => "grab",
            "grabbing" => "grabbing",
            _ => "default",
        }.to_string();
    }
    if normalized.starts_with("overflow.") {
        let v = normalized.rsplit('.').next().unwrap_or("");
        return match v {
            "visible" => "visible",
            "hidden" => "hidden",
            "scroll" => "scroll",
            "auto" => "auto",
            _ => "visible",
        }.to_string();
    }
    // Numeric size props
    if prop == "font_size" || prop == "border_radius" || prop == "gap"
        || prop == "line_height" || prop == "letter_spacing"
    {
        if val.chars().all(|c| c.is_ascii_digit() || c == '.') {
            return format!("{}px", val);
        }
    }
    // Handle transition(property, duration, easing)
    if prop == "transition" && val.trim().starts_with("transition(") {
        let inner = val.trim().trim_start_matches("transition(").trim_end_matches(')');
        let mut pv = "all".to_string();
        let mut du = "300ms".to_string();
        let mut ea = "ease".to_string();
        for part in inner.split(',') {
            let part = part.trim();
            if let Some(eq) = part.find(':') {
                let key = part[..eq].trim();
                let val_part = part[eq+1..].trim().trim_matches('"');
                match key {
                    "property" => pv = val_part.to_string(),
                    "duration" => du = format!("{}ms", val_part),
                    "easing" => ea = val_part.trim_start_matches("easing.").replace('_', "-"),
                    _ => {}
                }
            }
        }
        return format!("{} {} {}", pv, du, ea);
    }
    // Handle transform(scale_x, scale_y, rotate, ...)
    if prop == "transform" && val.trim().starts_with("transform(") {
        let inner = val.trim().trim_start_matches("transform(").trim_end_matches(')');
        let mut parts: Vec<String> = Vec::new();
        for part in inner.split(',') {
            let part = part.trim();
            if let Some(eq) = part.find(':') {
                let key = part[..eq].trim();
                let v = part[eq+1..].trim();
                let css = match key {
                    "scale_x" | "scale_y" => format!("scale({})", v),
                    "rotate" => format!("rotate({}deg)", v),
                    "translate_x" => format!("translateX({}px)", v),
                    "translate_y" => format!("translateY({}px)", v),
                    _ => String::new(),
                };
                if !css.is_empty() { parts.push(css); }
            }
        }
        return parts.join(" ");
    }
    // Direct hex colors
    if val.starts_with('#') || val == "white" || val == "black" || val == "transparent" {
        return val.to_string();
    }
    val.to_string()
}

fn to_media_condition(cond: &str) -> String {
    let c = cond.replace('_', "-");
    if c.contains(':') {
        format!("@media ({})", c)
    } else {
        format!("@media ({})", c)
    }
}

// ── Animation Generator ──────────────────────────────────────────

fn generate_animations(animations: &[AnimDecl]) -> String {
    let mut js = String::new();

    if animations.is_empty() {
        js.push_str("export const animations = {};\n\n");
        js.push_str("export function applyAnimation(el, animName) {\n");
        js.push_str("  const a = animations[animName];\n");
        js.push_str("  if (!a) return;\n");
        js.push_str("  el.animate(a.keyframes, a.options);\n");
        js.push_str("}\n\n");
        return js;
    }

    js.push_str("export const animations = {\n");
    for anim in animations {
        js.push_str(&format!("  '{}': {{\n", anim.name));
        js.push_str("    keyframes: [\n");

        let mut from = String::new();
        let mut to = String::new();
        let mut duration = 300i64;
        let mut easing = "ease".to_string();
        let mut iterations = 1i64;
        let mut delay = 0i64;
        let mut direction = "normal".to_string();
        let mut fill = "none".to_string();

        for prop in &anim.props {
            let v = prop.value.trim();
            match prop.name.as_str() {
                "duration" => { if let Ok(n) = v.parse::<i64>() { duration = n; } }
                "easing" => easing = to_js_easing(v),
                "delay" => { if let Ok(n) = v.parse::<i64>() { delay = n; } }
                "iterations" => { if let Ok(n) = v.parse::<i64>() { iterations = n; } }
                "direction" => direction = v.trim_matches('"').to_string(),
                "fill_mode" => fill = v.trim_matches('"').to_string(),
                "from" => from = parse_anim_state(v),
                "to" => to = parse_anim_state(v),
                _ => {}
            }
        }

        if !from.is_empty() {
            js.push_str(&format!("      {},\n", from));
        }
        if !to.is_empty() {
            js.push_str(&format!("      {},\n", to));
        }

        js.push_str("    ],\n");
        js.push_str("    options: {\n");
        js.push_str(&format!("      duration: {},\n", duration));
        js.push_str(&format!("      easing: '{}',\n", easing));
        js.push_str(&format!("      iterations: {},\n", iterations));
        if delay > 0 { js.push_str(&format!("      delay: {},\n", delay)); }
        if direction != "normal" { js.push_str(&format!("      direction: '{}',\n", direction)); }
        if fill != "none" { js.push_str(&format!("      fill: '{}',\n", fill)); }
        js.push_str("    },\n");
        js.push_str("  },\n");
    }
    js.push_str("};\n\n");

    js.push_str("export function applyAnimation(el, animName) {\n");
    js.push_str("  const a = animations[animName];\n");
    js.push_str("  if (!a) return;\n");
    js.push_str("  _a11y.animate(el, a.keyframes, a.options);\n");
    js.push_str("}\n\n");

    js
}

fn parse_anim_state(s: &str) -> String {
    let s = s.trim();
    if !s.starts_with("AnimationState(") {
        return "{}".to_string();
    }
    let inner = s.trim_start_matches("AnimationState(").trim_end_matches(')');
    let mut props = Vec::new();
    for part in inner.split(',') {
        let part = part.trim();
        if let Some(eq) = part.find(':') {
            let key = &part[..eq].trim();
            let val = &part[eq+1..].trim();
            let css_key = anim_prop_to_css(key);
            props.push(format!("'{}': {}", css_key, val));
        }
    }
    format!("{{{}}}", props.join(", "))
}

fn anim_prop_to_css(prop: &str) -> &str {
    match prop {
        "opacity" => "opacity",
        "translate_x" => "transform",
        "translate_y" => "transform",
        "scale_x" => "transform",
        "scale_y" => "transform",
        "rotate" => "transform",
        "background" => "backgroundColor",
        "color" => "color",
        "border_radius" => "borderRadius",
        "shadow" => "boxShadow",
        "width" => "width",
        "height" => "height",
        _ => prop,
    }
}

fn to_js_easing(easing: &str) -> String {
    match easing.trim() {
        "Easing.Linear" => "linear",
        "Easing.Ease" => "ease",
        "Easing.EaseIn" => "ease-in",
        "Easing.EaseOut" => "ease-out",
        "Easing.EaseInOut" => "ease-in-out",
        "Easing.EaseInSine" => "cubic-bezier(0.47, 0, 0.745, 0.715)",
        "Easing.EaseOutSine" => "cubic-bezier(0.39, 0.575, 0.565, 1)",
        "Easing.EaseInCubic" => "cubic-bezier(0.55, 0.055, 0.675, 0.19)",
        "Easing.EaseOutCubic" => "cubic-bezier(0.215, 0.61, 0.355, 1)",
        "Easing.Bounce" => "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        _ => "ease",
    }.to_string()
}

/// Translate a Kyle code block (@(...)) to basic JavaScript.
/// This is a temporary solution until the WASM bridge is implemented.
fn translate_kyle_block_to_js(block: &str) -> String {
    let mut js = String::new();
    let mut open_fns: Vec<usize> = Vec::new(); // track indentation of open functions
    let mut last_indent: Option<usize> = None;

    for raw_line in block.lines() {
        let indent = raw_line.len() - raw_line.trim_start().len();
        let line = raw_line.trim();
        last_indent = Some(indent);

        // Close functions when indentation decreases or matches parent
        // Must come BEFORE function definition/variable checks
        while let Some(&fn_indent) = open_fns.last() {
            if indent <= fn_indent && !open_fns.is_empty() {
                js.push_str("}\n");
                open_fns.pop();
            } else {
                break;
            }
        }

        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Compound assignment: "count += 1" → "state.set('count', state.get('count') + 1);"
        // MUST come before simple assignment check
        if line.contains("+=") || line.contains("-=") || line.contains("*=") || line.contains("/=") {
            let op = if line.contains("+=") { "+=" } else if line.contains("-=") { "-=" }
                     else if line.contains("*=") { "*=" } else { "/=" };
            if let Some(pos) = line.find(op) {
                let target = line[..pos].trim().trim_start_matches('@');
                let value = line[pos + 2..].trim();
                if !target.contains('(') && !target.contains(' ') && !target.starts_with("state.") {
                    let js_value = strip_at_refs(value);
                    js.push_str(&format!("  state.set('{}', state.get('{}') {} {});\n", target, target, &op[..1], js_value));
                } else {
                    js.push_str(&format!("  {} {} {};\n", target, op, value));
                }
                continue;
            }
        }

        // State initialization: "name := value" or "name: type = value" → "state.set('name', value);"
        // Only at top level (not inside function bodies)
        if open_fns.is_empty() && line.contains('=') && !line.starts_with("fn ") && !line.contains("==") {
            let eq_op = if line.contains(":=") { ":=" } else if line.contains('=') { "=" } else { "" };
            if !eq_op.is_empty() {
                if let Some(eq_pos) = line.find(eq_op) {
                    let target = line[..eq_pos].trim().trim_start_matches('@');
                    let value = line[eq_pos + eq_op.len()..].trim();
                    // Simple type annotation: name: type = value
                    if eq_op == "=" && line.contains(':') && !line.starts_with('@') {
                        if let Some(colon_pos) = line.find(':') {
                            let before_colon = line[..colon_pos].trim();
                            let after_colon = line[colon_pos + 1..].trim();
                            if after_colon.starts_with('^') || after_colon.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '&') {
                                if let Some(eq_pos2) = after_colon.find('=') {
                                    let ann = after_colon[..eq_pos2].trim();
                                    if ann.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '^' || c == '&' || c == '{' || c == '}' || c == '<' || c == '>') {
                                        let value2 = after_colon[eq_pos2 + 1..].trim().trim_start_matches('@');
                                        js.push_str(&format!("state.set('{}', {});\n", before_colon, value2));
                                        continue;
                                    }
                                }
                            }
                        }
                    }
                    // name := value or @name = value
                    let js_value = strip_at_refs(value);
                    js.push_str(&format!("state.set('{}', {});\n", target, js_value));
                    continue;
                }
            }
        }

        // Function definition: "fn name(args):" → "const name = (args) => {"
        if line.starts_with("fn ") {
            let rest = line.trim_start_matches("fn ").trim();
            if let Some(paren_pos) = rest.find('(') {
                let name = rest[..paren_pos].trim();
                let params_end = rest.rfind(')').unwrap_or(rest.len());
                let raw_params = &rest[paren_pos..=params_end];
                // Strip type annotations from params: (event: click_event) → (event)
                let params = raw_params.split(',').map(|p| {
                    let p = p.trim_start_matches('(').trim_end_matches(')').trim();
                    if let Some(colon) = p.find(':') {
                        p[..colon].trim()
                    } else {
                        p
                    }
                }).collect::<Vec<_>>().join(", ");
                let params_str = format!("({})", params);
                js.push_str(&format!("const {} = {} => {{\n", name, params_str));
                open_fns.push(indent);
            }
            continue;
        }

        // Function body: "count = count + 1" → "state.set('count', state.get('count') + 1);"
        if line.contains('=') && !line.contains("==") {
            if let Some(eq_pos) = line.find('=') {
                let target = line[..eq_pos].trim().trim_start_matches('@');
                let value = line[eq_pos + 1..].trim();
                if !target.contains('(') && !target.contains(' ') && !target.starts_with("state.") {
                    let js_value = kyle_to_js_expr(value);
                    js.push_str(&format!("  state.set('{}', {});\n", target, js_value));
                } else {
                    js.push_str(&format!("  {} = {};\n", target, value));
                }
            }
            continue;
        }

        // Plain expression
        let trimmed_line = line.strip_suffix(':').unwrap_or(line).trim_start_matches('@');
        if trimmed_line.starts_with("if ") {
            let cond = &trimmed_line[3..].trim().trim_end_matches(':');
            js.push_str(&format!("  if ({}) {{\n", kyle_to_js_expr(cond)));
            open_fns.push(indent);
        } else {
            js.push_str(&format!("{}\n", kyle_to_js_expr(trimmed_line)));
        }
    }

    // Close any remaining open functions
    while !open_fns.is_empty() {
        js.push_str("};\n");
        open_fns.pop();
    }

    js
}

/// Known JS/Kyle built-in identifiers that should NOT be replaced with state.get()
const JS_BUILTINS: &[&str] = &[
    "true", "false", "null", "undefined",
    "state", "navigate", "set_title", "set_meta", "routeParams",
    "navigate_back", "navigate_replace",
    "if", "else", "for", "while", "return", "fn",
    "new", "this", "typeof", "instanceof", "in", "of",
    "console", "window", "document",
    "Math", "JSON", "Array", "Object", "String", "Number",
    "Boolean", "Map", "Set", "Promise", "Error",
    "parseInt", "parseFloat", "isNaN", "isFinite",
    "event", "e", "file", "fileData", "files",
    "el", "container", "params",
    "toast", "dialog", "storage", "confirm", "alert", "prompt",
    "set_title", "set_meta", "routeParams", "navigate", "navigate_back", "navigate_replace",
    "current_theme", "current_breakpoint", "set_locale",
    "set_interval", "clear_interval", "set_timeout", "clear_timeout",
];

/// Check if a token is a known JS/Kyle built-in (not a state variable)
fn is_builtin(token: &str) -> bool {
    JS_BUILTINS.contains(&token)
}

/// Extract potential state variable names from an expression.
fn extract_state_keys(expr: &str) -> Vec<String> {
    let mut keys = Vec::new();
    let mut current = String::new();
    let mut in_string = false;
    let mut after_dot = false;
    let mut chars = expr.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '"' || c == '\'' {
            in_string = !in_string;
            flush_ident(&mut current, &mut keys, after_dot);
            after_dot = false;
            continue;
        }
        if in_string {
            continue;
        }
        if c.is_alphanumeric() || c == '_' {
            current.push(c);
        } else {
            if c == '.' {
                // Flush the identifier before the dot (respect after_dot state)
                flush_ident(&mut current, &mut keys, after_dot);
                after_dot = true;
            } else {
                // Flush and don't treat as state var if after dot
                flush_ident(&mut current, &mut keys, after_dot);
                after_dot = false;
            }
        }
    }
    flush_ident(&mut current, &mut keys, after_dot);
    keys
}

fn flush_ident(current: &mut String, keys: &mut Vec<String>, after_dot: bool) {
    if !current.is_empty() {
        let token = current.clone();
        if !after_dot && !is_builtin(&token) {
            keys.push(token);
        }
        current.clear();
    }
}

/// Translate a Kyle expression to JS, replacing state vars with state.get()
fn kyle_to_js_expr(expr: &str) -> String {
    // Phase 1: shorten Kyle method names to JS equivalents
    let mut result = expr.to_string();
    result = result.replace(".to_str()", ".toString()");
    result = result.replace(".to_string()", ".toString()");
    result = result.replace(".len()", ".length");
    result = result.replace(".is_empty()", " === ''");
    result = result.replace(".contains(", ".includes(");

    // Phase 1b: Convert Kyle set literals {a,b,c} to JS arrays [a,b,c]
    // Keep object literals {k:v} as-is
    result = convert_set_literals(&result);

    // Phase 2: Replace state variable references with state.get('var')
    // We scan for identifiers (outside strings) and wrap them in state.get()
    let mut out = String::new();
    let mut current = String::new();
    let mut in_string = false;
    let mut after_dot = false;
    let mut chars = result.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '"' || c == '\'' {
            flush_token(&mut current, &mut out, after_dot, true);
            in_string = !in_string;
            out.push(c);
            after_dot = false;
            continue;
        }
        if in_string {
            out.push(c);
            continue;
        }
        // Strip Kyle @ prefix before string literals: @"text" → "text"
        if c == '@' {
            let next = chars.peek();
            if next == Some(&'"') {
                continue; // skip @ before string
            }
        }
        if c.is_alphanumeric() || c == '_' {
            current.push(c);
        } else {
            if c == '(' {
                // Function call — don't wrap function name if it's after a dot (method call)
                flush_token(&mut current, &mut out, after_dot, false);
                out.push(c);
                after_dot = false;
            } else if c == '.' {
                flush_token(&mut current, &mut out, after_dot, false);
                after_dot = true;
                out.push(c);
            } else {
                flush_token(&mut current, &mut out, after_dot, false);
                out.push(c);
                after_dot = false;
            }
        }
    }
    flush_token(&mut current, &mut out, after_dot, false);

    out
}

/// Convert Kyle set literals {a,b,c} to JS arrays [a,b,c].
/// Dict literals {k:v} are kept as-is.
fn convert_set_literals(s: &str) -> String {
    let mut out = String::new();
    let mut chars = s.chars().peekable();
    let mut in_string = false;
    let mut brace_start = None;

    while let Some(c) = chars.next() {
        if c == '"' || c == '\'' {
            if brace_start.is_some() {
                in_string = !in_string;
                out.push(c);
            } else {
                out.push(c);
                in_string = !in_string;
            }
            continue;
        }
        if in_string {
            out.push(c);
            continue;
        }
        if c == '{' && brace_start.is_none() {
            brace_start = Some(out.len() as i32);
            out.push(c);
            continue;
        }
        if c == '}' {
            if let Some(start) = brace_start {
                let full: String = out[start as usize..].chars().collect();
                let inner = &full[1..]; // content between { and }
                if !inner.is_empty() && inner.contains(',') && !contains_top_level_colon(inner) {
                    out.truncate(start as usize);
                    out.push('[');
                    out.push_str(inner);
                    out.push(']');
                } else {
                    out.push(c);
                }
                brace_start = None;
            } else {
                out.push(c);
            }
            continue;
        }
        out.push(c);
    }
    out
}

/// Check if a string contains a colon at the top level (not inside nested braces or strings).
fn contains_top_level_colon(s: &str) -> bool {
    let mut depth = 0;
    let mut in_str = false;
    for c in s.chars() {
        if c == '"' || c == '\'' { in_str = !in_str; continue; }
        if in_str { continue; }
        match c {
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => depth -= 1,
            ':' if depth == 0 => return true,
            _ => {}
        }
    }
    false
}

fn flush_token(current: &mut String, out: &mut String, after_dot: bool, in_string: bool) {
    if !current.is_empty() {
        let token = current.clone();
        let is_numeric = token.chars().all(|c| c.is_ascii_digit() || c == '.' || c == '-');
        if after_dot || in_string || is_builtin(&token) || token.starts_with("state.") || is_numeric {
            out.push_str(&token);
        } else {
            out.push_str(&format!("state.get('{}')", token));
        }
        current.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_web_backend_generates_js() {
        let backend = WebBackend::new();
        let program = UiProgram {
            routes: vec![],
            code_blocks: vec![],
            styles: vec![],
            animations: vec![],
            component_renderers: vec![],
            body: vec![UiNode::SelfClosing {
                tag: ComponentTag::Text,
                attrs: vec![UiAttr {
                    name: "value".to_string(),
                    value: AttrValue::String("Hello".to_string()),
                }],
            }],
        };
        let output = backend.generate(&program);
        assert!(output.files.len() == 1);
        assert!(output.files[0].content.contains("createElement"));
        assert!(output.files[0].content.contains("Hello"));
        assert!(output.html_shell.is_some());
        let html = output.html_shell.unwrap();
        assert!(html.contains("<script type=\"module\">"));
    }

    #[test]
    fn test_style_generation() {
        let styles = vec![StyleDecl::Style {
            component: "button".to_string(),
            name: "Primary".to_string(),
            props: vec![
                StyleProp { name: "background".to_string(), value: "Color(\"#0066FF\")".to_string() },
                StyleProp { name: "color".to_string(), value: "Color(\"#FFFFFF\")".to_string() },
                StyleProp { name: "border_radius".to_string(), value: "8".to_string() },
            ],
            media: vec![],
        }];
        let js = generate_styles(&styles);
        assert!(js.contains("Primary"));
        assert!(js.contains("export function applyStyle"));
    }

    #[test]
    fn test_animation_generation() {
        let anims = vec![AnimDecl {
            component: "view".to_string(),
            name: "FadeIn".to_string(),
            props: vec![
                StyleProp { name: "duration".to_string(), value: "300".to_string() },
                StyleProp { name: "easing".to_string(), value: "Easing.EaseOut".to_string() },
                StyleProp { name: "from".to_string(), value: "AnimationState(opacity: 0.0)".to_string() },
                StyleProp { name: "to".to_string(), value: "AnimationState(opacity: 1.0)".to_string() },
            ],
        }];
        let js = generate_animations(&anims);
        assert!(js.contains("export const animations"));
        assert!(js.contains("export function applyAnimation"));
    }

    #[test]
    fn test_kyle_to_js_expr_simple_var() {
        let result = kyle_to_js_expr("count");
        assert_eq!(result, "state.get('count')");
    }

    #[test]
    fn test_kyle_to_js_expr_method_call() {
        let result = kyle_to_js_expr("count.to_str()");
        assert_eq!(result, "state.get('count').toString()");
    }

    #[test]
    fn test_kyle_to_js_expr_with_string() {
        let result = kyle_to_js_expr("\"Hello \" + name");
        assert_eq!(result, "\"Hello \" + state.get('name')");
    }

    #[test]
    fn test_kyle_to_js_expr_builtin_skipped() {
        let result = kyle_to_js_expr("true");
        assert_eq!(result, "true");
    }

    #[test]
    fn test_kyle_to_js_expr_event_param() {
        let result = kyle_to_js_expr("event.x.to_str()");
        assert_eq!(result, "event.x.toString()");
    }

    #[test]
    fn test_kyle_to_js_expr_chained_methods() {
        let result = kyle_to_js_expr("user.name.to_upper()");
        assert_eq!(result, "state.get('user').name.to_upper()");
    }

    #[test]
    fn test_kyle_to_js_expr_arithmetic() {
        let result = kyle_to_js_expr("count + 1");
        assert_eq!(result, "state.get('count') + 1");
    }

    #[test]
    fn test_kyle_to_js_expr_len_conversion() {
        let result = kyle_to_js_expr("items.len()");
        assert_eq!(result, "state.get('items').length");
    }

    #[test]
    fn test_kyle_to_js_expr_is_empty() {
        let result = kyle_to_js_expr("name.is_empty()");
        assert_eq!(result, "state.get('name') === ''");
    }

    #[test]
    fn test_kyle_to_js_expr_contains() {
        let result = kyle_to_js_expr("email.contains('@')");
        assert_eq!(result, "state.get('email').includes('@')");
    }

    #[test]
    fn test_extract_state_keys_simple() {
        let keys = extract_state_keys("count");
        assert_eq!(keys, vec!["count"]);
    }

    #[test]
    fn test_extract_state_keys_with_method() {
        let keys = extract_state_keys("count.to_str()");
        assert_eq!(keys, vec!["count"]);
    }

    #[test]
    fn test_extract_state_keys_multi() {
        let keys = extract_state_keys("first_name + \" \" + last_name");
        assert!(keys.contains(&"first_name".to_string()));
        assert!(keys.contains(&"last_name".to_string()));
    }

    #[test]
    fn test_extract_state_keys_skips_builtins() {
        let keys = extract_state_keys("event.x + count");
        assert_eq!(keys, vec!["count"]);
    }

    #[test]
    fn test_extract_state_keys_complex() {
        let keys = extract_state_keys("user.name.to_str()");
        assert_eq!(keys, vec!["user"]);
    }

    #[test]
    fn test_translate_block_state_init() {
        let js = translate_kyle_block_to_js("count: ^i32 = 0");
        assert!(js.contains("state.set('count', 0)"));
    }

    #[test]
    fn test_translate_block_function_def() {
        let js = translate_kyle_block_to_js("fn increment():\n    count += 1");
        assert!(js.contains("const increment = () => {"));
        assert!(js.contains("state.get('count') + 1"));
    }

    #[test]
    fn test_translate_block_compound() {
        let js = translate_kyle_block_to_js("count += 1");
        assert!(js.contains("state.set('count', state.get('count') + 1)"));
    }

    #[test]
    fn test_translate_block_simple_assign() {
        let js = translate_kyle_block_to_js("name = \"test\"");
        assert!(js.contains("state.set('name', \"test\")"));
    }

    #[test]
    fn test_is_builtin_recognizes_event() {
        assert!(is_builtin("event"));
        assert!(is_builtin("toast"));
        assert!(is_builtin("navigate"));
        assert!(is_builtin("console"));
        assert!(!is_builtin("count"));
        assert!(!is_builtin("items"));
    }

    #[test]
    fn test_js_tag_mapping() {
        assert_eq!(js_tag(&ComponentTag::Button), "button");
        assert_eq!(js_tag(&ComponentTag::Text), "span");
        assert_eq!(js_tag(&ComponentTag::Image), "img");
        assert_eq!(js_tag(&ComponentTag::List), "ul");
        assert_eq!(js_tag(&ComponentTag::Form), "form");
        assert_eq!(js_tag(&ComponentTag::View), "div");
        assert_eq!(js_tag(&ComponentTag::TextField), "input");
        assert_eq!(js_tag(&ComponentTag::Checkbox), "input");
        assert_eq!(js_tag(&ComponentTag::Slider), "input");
        assert_eq!(js_tag(&ComponentTag::Progress), "progress");
    }

    #[test]
    fn test_style_attr_to_css_mapping() {
        assert_eq!(style_attr_to_css("font_size"), Some("'fontSize'".to_string()));
        assert_eq!(style_attr_to_css("border_radius"), Some("'borderRadius'".to_string()));
        assert_eq!(style_attr_to_css("background_color"), Some("'backgroundColor'".to_string()));
        assert_eq!(style_attr_to_css("margin"), Some("'margin'".to_string()));
        assert_eq!(style_attr_to_css("transition"), Some("'transition'".to_string()));
        assert_eq!(style_attr_to_css("unknown_prop"), None);
    }

    #[test]
    fn test_event_name_mapping() {
        // Test that the event name mapping matches expected JS events
        let check = |name: &str, expected: &str| {
            match name {
                "click" => assert_eq!("click", expected),
                "mouse_enter" => assert_eq!("mouseenter", expected),
                "mouse_leave" => assert_eq!("mouseleave", expected),
                "touch_start" => assert_eq!("touchstart", expected),
                "touch_end" => assert_eq!("touchend", expected),
                "touch_move" => assert_eq!("touchmove", expected),
                "long_press" => assert_eq!("longpress", expected),
                "dblclick" => assert_eq!("dblclick", expected),
                "keydown" => assert_eq!("keydown", expected),
                "submit" => assert_eq!("submit", expected),
                _ => {}
            }
        };
        check("click", "click");
        check("mouse_enter", "mouseenter");
        check("touch_start", "touchstart");
        check("long_press", "longpress");
    }

    #[test]
    fn test_interpolate_state_simple() {
        let result = interpolate_state("@name");
        assert_eq!(result, "state.get(\"name\")");
    }

    #[test]
    fn test_interpolate_state_with_text() {
        let result = interpolate_state("Hello @name");
        assert_eq!(result, "\"Hello \" + state.get(\"name\")");
    }

    #[test]
    fn test_interpolate_state_multi() {
        let result = interpolate_state("@first @last");
        assert_eq!(result, "state.get(\"first\") + \" \" + state.get(\"last\")");
    }
}
